### PR TITLE
Remove DLNA configuration pages pages

### LINKED ISSUE #5234: DLNA options visible in dashboard when plugin is not installed
**Describe The Bug**

In Jellyfin 10.9 the DLNA functionality is moved to a plugin. This plugin is not installed by default.

However, right now if you navigate to the dashboard it still shows the DLNA settings. Opening these pages will make jellyfin-web load indefinitely.

**Expected Behavior**

No DLNA pages available.

**Logs**

web

DLNA Settings page

```
Uncaught (in promise) 
Response { type: "cors", url: "http://127.0.0.1:8097/System/Configuration/dlna", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers(1), body: ReadableStream, bodyUsed: false }
```

DLNA Profiles page

```
Uncaught (in promise) 
Response { type: "cors", url: "http://127.0.0.1:8097/Dlna/ProfileInfos", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers(1), body: ReadableStream, bodyUsed: false }
```

server (unrelated I guess)
```
[14:38:33] [ERR] [26] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /System/Configuration/dlna.
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key dlna not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c.<GetConfiguration>b__41_0(String k, BaseConfigurationManager configurationMana
ger) in Emby.Server.Implementations\AppBase\BaseConfigurationManager.cs:line 292
```
**Screenshots**

94900002cd

**System (please complete the following information):**
 - Platform: All
 - Browser: All
 - Jellyfin Version: 10.9.0 master branch at 2024-02-27

**Additional Context**

Not sure what the best solution here is. We could move the web part for DLNA to the plugin but that would make it hard to maintain and integrate in the new React magic. So perhaps we should look if the plugin is installed&enabled and conditionally show these pages? We'd need to make sure that they also don't work when opening the pages directly.

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Removes the DLNA configuration pages and replaces them with a page instructing them to install the plugin (similar to what was done for notifications). I also adjusted the UI of the notifications page to match (using the mui Alert and components and directly using react-router-dom for linking).

Screen Shot 2024-03-04 at 13 50 47-fullpage
Screen Shot 2024-03-04 at 13 50 21-fullpage

**Issues**
Fixes #5234

### CODE REVIEW

File: src/apps/dashboard/routes/notifications.tsx [hunk 1]
```diff
@@ -1,36 +1,34 @@
...
-            </p>
-            <PluginLink />
+
+            <Alert severity='info'>
+                <Box sx={{ marginBottom: 2 }}>
+                    {globalize.translate('NotificationsMovedMessage')}
+                </Box>
+                <Button
+                    component={Link}
+                    to='/dashboard/plugins/add?name=Webhook&guid=71552a5a5c5c4350a2aeebe451a30173'
```
Comment (nielsvanvelzen) [inline src/apps/dashboard/routes/notifications.tsx:25]: Slightly unrelated, when you don't have a repository that includes this specific plugin the page will fail to load. We should probably show some error on it.

Comment (nielsvanvelzen) [reply src/apps/dashboard/routes/notifications.tsx:25]: Yeah definitely for a separate PR, just wanted to let you know

**Review by nielsvanvelzen — APPROVED** [review]
