### PR TITLE
Fix missing emby-collapse import in add plugin page

### LINKED ISSUE #5335: Dashboard plugin page styling regression
**Describe The Bug**
Some styling of the elements on the "addplugin.html" page is kind of broken in current unstable. See screenshots of the ldap plugin:

### 10.8.13
image

### 10.9

The expandable sections are no longer expandable (they just show), have no title and don't have any padding.

**Steps To Reproduce**

- Open a plugin from the catalog in dashboard

**Expected Behavior**

- Slightly more fancy design

**Logs**

**Screenshots**
See above

**System (please complete the following information):**

 - Jellyfin Version: 10.9

**Additional Context**

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Fixes a missing import for the `emby-collapse` element on the add plugin page

**Issues**
Fixes #5335

### CODE REVIEW

File: src/controllers/dashboard/plugins/add/index.js [hunk 1]
```diff
@@ -3,11 +3,13 @@ import markdownIt from 'markdown-it';
 import DOMPurify from 'dompurify';
 import loading from '../../../../components/loading/loading';
 import globalize from '../../../../scripts/globalize';
-import '../../../../elements/emby-button/emby-button';
 import Dashboard from '../../../../utils/dashboard';
 import alert from '../../../../components/alert';
 import confirm from '../../../../components/confirm/confirm';
 
+import 'elements/emby-button/emby-button';
+import 'elements/emby-collapse/emby-collapse';
```
Comment (dmitrylyzo) [inline src/controllers/dashboard/plugins/add/index.js:11]: There is `emby-select` in the template. I think we should import it as well.

**Review by dmitrylyzo — APPROVED** [review]
