### PR TITLE
Enable and fix PiP for Safari

### LINKED ISSUE #101: Picture-in-picture support on macOS
High Sierra and Mojave have a support for native PIP (works at least in Chrome and Safari). Youtube seems to have this implemented. This may work in video.js (#142) but I'm not 100% confident about that. It's also described in detail on Apple developers page and seems fairly easy to implemented :) Would be nice to have this, although it's mostly QoL. Thanks!

Ref: https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls

### PR DESCRIPTION
**Pull request by anthonylavado**
This enables the previously commented out lines that would enable Picture in Picture support for Safari.
Also fixed IF condition to match the Apple developer reccomendation: https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls

Fixes #101.

### CODE REVIEW

**Comment by anthonylavado** [comment]
Tested working in Safari Version 12.0.3 (14606.4.5) on macOS Mojave 10.14.3 (18D42).

File: src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js [hunk 1]
```diff
@@ -1443,9 +1443,9 @@ define(['browser', 'require', 'events', 'apphost', 'loading', 'dom', 'playbackMa
         var list = [];
 
         var video = document.createElement('video');
-        //if (video.webkitSupportsPresentationMode && video.webkitSupportsPresentationMode('picture-in-picture') && typeof video.webkitSetPresentationMode === "function") {
-        //    list.push('PictureInPicture');
-        //}
+        if (video.webkitSupportsPresentationMode && typeof video.webkitSetPresentationMode === "function") {
```
Comment (JustAMan) [inline src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]: Can you merge two `if`s in one?

Comment (dkanada) [reply src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]: Yeah you definitely can, this will be fine.

Comment (anthonylavado) [reply src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]: This is the way Apple describes this exact line for this function - and it has worked in my testing.

Comment (anthonylavado) [reply src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]: Okay, I realized earlier in the Chat that I was misunderstanding the question here. I was only looking at the single highlighted line, and not looking further.

I have done some testing, and implemented some changes in https://github.com/jellyfin/jellyfin-web/pull/118/commits/c99f9c6d656e2259f90b2995074d11e78b5104d6. Let me know if that works.

File: src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js [hunk 2]
```diff
@@ -1443,12 +1443,10 @@ define(['browser', 'require', 'events', 'apphost', 'loading', 'dom', 'playbackMa
         var list = [];
 
         var video = document.createElement('video');
-        //if (video.webkitSupportsPresentationMode && video.webkitSupportsPresentationMode('picture-in-picture') && typeof video.webkitSetPresentationMode === "function") {
-        //    list.push('PictureInPicture');
-        //}
-        if (document.pictureInPictureEnabled) {
+        if ((video.webkitSupportsPresentationMode && typeof video.webkitSetPresentationMode === "function") || (document.pictureInPictureEnabled)) {
```
Comment (cvium) [inline src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]: Unnecessary parentheses
```suggestion
        if (video.webkitSupportsPresentationMode && typeof video.webkitSetPresentationMode === "function" || document.pictureInPictureEnabled) {
```

File: src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js [hunk 3]
```diff
@@ -1443,12 +1443,10 @@ define(['browser', 'require', 'events', 'apphost', 'loading', 'dom', 'playbackMa
...
 
         var video = document.createElement('video');
-        //if (video.webkitSupportsPresentationMode && video.webkitSupportsPresentationMode('picture-in-picture') && typeof video.webkitSetPresentationMode === "function") {
-        //    list.push('PictureInPicture');
-        //}
-        if (document.pictureInPictureEnabled) {
+        if (video.webkitSupportsPresentationMode && typeof video.webkitSetPresentationMode === "function" || document.pictureInPictureEnabled) {
             list.push('PictureInPicture');
         }
+
```
Comment (cvium) [inline src/bower_components/emby-webcomponents/htmlvideoplayer/plugin.js]:
```suggestion
```
