### PR TITLE
Don’t bind to keyevents of media keys when browser support mediaSession

### LINKED ISSUE #5523: Stacking Playback error popup when advancing with media keys
**Describe The Bug**
When advancing to the next song or episode by pressing the keyboard media keys, a playback error popup is shown in the web UI. The media goes to the next track/episode as expected. Repeatedly pressing the media key stacks the popups infinitely.

**Steps To Reproduce**
1. Start playback of some series of music or video.
2. Press the keyboard Next or Previous buttons.
3. The media advances to the next or previous track/episode as expected.
4. A playback error popup appears.
5. Repeating this, more playback error popups stack.

**Expected Behavior**
The playback error popup seems to be wrong as the media is playing back fine. This also does not occur when clicking the next or previous buttons in the UI.

**Logs**
JS console log when pressing Next

```
playing next track main.jellyfin.bundle.js:2:157876
Requesting https://█████████████████/Users/b16696279473411ab1d9655898cb2bcc/Items/274f10664d721e020e17d92995c68a5e node_modules.jellyfin-apiclient.bundle.js:2:13545
Requesting url without automatic networking: https://█████████████████/Sessions/Playing/Stopped node_modules.jellyfin-apiclient.bundle.js:2:14622
AutoSet Subtitle - No Stream Set 2 main.jellyfin.bundle.js:2:143117
playing url: https://█████████████████/Audio/65cf8018c5981fc73f34027e6e9369be/universal?UserId=b16696279473411ab1d9655898cb2bcc&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE1LjB8MTY5MTE5MjI2ODM5OQ11&MaxStreamingBitrate=214151189&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=c50be418d84e413ca52f7e368f663076&PlaySessionId=1715894383625&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false htmlAudioPlayer-plugin.fedaf1ff57bcd0f2bd5f.chunk.js:2:9868
gain: 1 htmlAudioPlayer-plugin.fedaf1ff57bcd0f2bd5f.chunk.js:2:10291
requesting url: https://█████████████████/Audio/65cf8018c5981fc73f34027e6e9369be/universal?UserId=b16696279473411ab1d9655898cb2bcc&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE1LjB8MTY5MTE5MjI2ODM5OQ11&MaxStreamingBitrate=214151189&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=c50be418d84e413ca52f7e368f663076&PlaySessionId=1715894383625&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false 56079.dfaf85de5fa2c0924fad.chunk.js:1:2308
response status: 200, url: https://█████████████████/Audio/65cf8018c5981fc73f34027e6e9369be/universal?UserId=b16696279473411ab1d9655898cb2bcc&DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTE1LjB8MTY5MTE5MjI2ODM5OQ11&MaxStreamingBitrate=214151189&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=c50be418d84e413ca52f7e368f663076&PlaySessionId=1715894383625&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false 56079.dfaf85de5fa2c0924fad.chunk.js:1:2386
Active player: {"name":"Html Audio Player","id":"htmlaudioplayer","playerName":"Html Audio Player","playableMediaTypes":[true,false,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","SetShuffleQueue","PlayMediaSource","PlayTrailers","ToggleFullscreen","PlaybackRate"]} main.jellyfin.bundle.js:2:114683
nowplaying event: playbackstart 18084.239da02d76e26fda517e.chunk.js:1:9330
[nowPlayingBar:onStateChanged] event: playbackstart 18084.239da02d76e26fda517e.chunk.js:1:10036
Requesting https://█████████████████/Users/b16696279473411ab1d9655898cb2bcc/Items/65cf8018c5981fc73f34027e6e9369be node_modules.jellyfin-apiclient.bundle.js:2:13545
Requesting url without automatic networking: https://█████████████████/Sessions/Playing node_modules.jellyfin-apiclient.bundle.js:2:14622
Requesting url without automatic networking: https://█████████████████/Sessions/Playing/Progress node_modules.jellyfin-apiclient.bundle.js:2:14622
Sending web socket message: KeepAlive
```

**Screenshots**

**System (please complete the following information):**
 - Server OS: Linux
 - Client OS: Windows (not on Linux, I checked)
 - Browser: Firefox
 - Jellyfin Version: 10.9.1

**Additional Context**

https://github.com/jellyfin/jellyfin-web/assets/39026963/f1b360ac-1620-47dc-851f-dd886fe9e86b

### PR DESCRIPTION
**Pull request by gnattu**
These events are already handled by MediaSession. On some operating systems, like Windows, the browser will send both the MediaSession event and the keydown event to the webpage, causing the event to be handled twice and resulting in issues.

**Changes**

Remove media key binding in keyboardNavigation

**Issues**

Fixes #5523

### CODE REVIEW

**Comment by dmitrylyzo** [comment]
This needs to be tested on TV with keyboard connected. `keyboardNavigation.js` is primarily for TV.

**Comment by dmitrylyzo** [comment]
We could do something like this:
```js
const hasMediaSession = 'mediaSession' in navigator;

...

case 'MediaPlayPause':
    if (!hasMediaSession) inputManager.handleCommand('playpause');
    break;
```
But I have no idea if modern TVs have `MediaSession`.

**Comment by gnattu** [comment]
> But I have no idea if modern TVs have MediaSession.

Even if they do, is it really reliable is also questionable.

Do we have the double event issue for TV yet? If we don't then probably one of the event handler is not really working for the TVs, but which one is unknown.

**Comment by dmitrylyzo** [comment]
I'm sure `keydown` works for `Media*` keys on Tizen - that's how Samsung recommends handling them.
https://developer.samsung.com/smarttv/develop/api-references/tizen-web-device-api-references/tvinputdevice-api.html
```js
var i, keyCode = {}, supportedKeys;
supportedKeys = tizen.tvinputdevice.getSupportedKeys();
for (i = 0; i < supportedKeys.length; i++) {
    keyCode[supportedKeys[i].name] = supportedKeys[i].code;
}
if(keyCode.hasOwnProperty("ChannelUp")) {
    tizen.tvinputdevice.registerKey("ChannelUp");
}
window.addEventListener("keydown", function(keyEvent) {
    // identify the key by the numeric code from the keyEvent
    if(keyEvent.keyCode === keyCode.ChannelUp) {
        console.log("The CHANNEL UP was pressed");
    }
});
```

After a quick look, there is no MediaSession API.
https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

**Comment by gnattu** [comment]
@GeorgeH005 Can you do me a favor for this as well? Can you test if webOS have MediaSession and is its MediaSession reliable? So that we can have some level of confidence for two major smart TV platforms.

**Comment by gnattu** [comment]
Updated to make the compatibility better. Now it only binds media keys on TV and browsers not having mediaSession. Should work good enough and cover most use cases.

File: src/scripts/keyboardNavigation.js [hunk 1]
```diff
@@ -116,6 +131,11 @@ export function enable() {
             return;
         }
 
+        // Ignore Media Keys for non-TV platform having MediaSession API
+        if (!layoutManager.tv && isMediaKey(key) && 'mediaSession' in navigator) {
```
Comment (dmitrylyzo) [inline src/scripts/keyboardNavigation.js:135]: I wonder which is faster, `... in ...` or a const (defined in the beginning of `enable`)? Nanoseconds (maybe a little more on old hardware or TVs), but still.

**Review by dmitrylyzo — APPROVED** [review]

File: src/scripts/keyboardNavigation.js [hunk 2]
```diff
@@ -116,6 +132,11 @@ export function enable() {
             return;
         }
 
+        // Ignore Media Keys for non-TV platform having MediaSession API
+        if (!layoutManager.tv && isMediaKey(key) && hasMediaSession) {
```
Comment (dmitrylyzo) [inline src/scripts/keyboardNavigation.js:136]: Overlooked this. We can activate TV layout on the PC. We should test the browser "type".
```suggestion
        if (!browser.tv && isMediaKey(key) && hasMediaSession) {
```

**Review by dmitrylyzo — CHANGES_REQUESTED** [review]

**Review by dmitrylyzo — APPROVED** [review]
