### PR TITLE
Remove click action from item details primary image

### LINKED ISSUE #4234: Web client tries to play nonexistent media when clicking on actor photo
**Describe The Bug**
In all the Jellyfin web clients I've tried, when I click/tap on an actor under a show's Cast & Crew heading, it brings me to the details page for that actor (as expected). When I then clicked the actor's portrait photo, I get a popup dialog with the error message "No player found for the requested media."

**Steps To Reproduce**
1. Go to an actor's details page
2. Click/tap on the actor's main portrait on the left
3. Error is displayed

**Expected Behavior**
I expected it to show a bigger version of that picture.

**Logs**
There are no pertinent log messages.

**Screenshots**
image

**System (please complete the following information):**
 - Platform: Windows, Android, iOS
 - Browser: Firefox 108.0.1, official Android app, official iOS app
 - Jellyfin Version: 10.8.8

**Additional Context**
N/A

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
* Adds a new function to build an image only card without any additional functionality
* Changes the item details primary image to use this function
* Removes click handling on the primary image

**Issues**
This was called out by the new ui/ux team as being a major issue on the item details page.
Fixes #4234 
Supersedes #4272

### CODE REVIEW

File: src/components/cardbuilder/cardImage.ts [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    let blurhashAttrib = '';
+    if (blurhash && blurhash.length > 0) {
+        blurhashAttrib = `data-blurhash="${blurhash}"`;
+    }
+
+    return (
+        `<div class="card ${className}">
+    <div class="cardBox">
+        <div class="cardScalable">
+            <div class="cardPadder cardPadder-${shape}"></div>
```
Comment (dmitrylyzo) [inline src/components/cardbuilder/cardImage.ts:50]: Should we add an [icon](https://github.com/jellyfin/jellyfin-web/blob/408b7c011a8534b58d99e0a5ffead5ef9b506ec3/src/components/cardbuilder/cardBuilder.js#L1112-L1119) when blurhash is disabled?

Comment (thornbill) [reply src/components/cardbuilder/cardImage.ts]: I (finally) updated this to include the icon logic.

File: src/components/cardbuilder/cardImage.ts [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+    const image = getCardImageUrl(
+        item,
+        apiClient,
+        options,
+        shape
+    );
+
+    if (!image) return '';
+
+    const className = ` ${shape}Card`;
```
Comment (dmitrylyzo) [inline src/components/cardbuilder/cardImage.ts:39]: _nitpicking_
```suggestion
    const className = `${shape}Card`;
```
The space is in the output string.

Comment (thornbill) [reply src/components/cardbuilder/cardImage.ts]: I just removed this variable since it is only used in one place anyway

**Review by dmitrylyzo — APPROVED** [review]
