### PR TITLE
Fix changing filters not resetting multiselected media cards

### LINKED ISSUE #5209: Changing filters while in selection mode, doesn't cancel selection mode completely
**Describe The Bug**
If you long press (touch or click) a video and enter selection mode, after changing filters, the selection remains, it should be cleared.

**Steps To Reproduce**

1. Go to a library
2. Long Click on a movie or episode until selection checkboxes turn on.
3. Select a few items.
4. Change filters (click on the filter icon, change any filter on, then off)
5. Selection checkboxes disappear but the top bar with cross, number of selected items, and three dot menu remains.
6. See error

**Expected Behavior**
When changing filters, clear any selection and remove the top bar.

**Screenshots**

https://github.com/jellyfin/jellyfin-web/assets/2464891/d5586266-695d-4880-b0c6-add9ff469563

**System:**
 - Platform: Windows 11
 - Browser: Any browser.
 - Jellyfin Version: [10.8.13]

### PR DESCRIPTION
**Pull request by ConnorS1110**
**Changes**
Multi-selected options are now cleared by calling `hideSelections` from the `multiSelect` component when a change is triggered in the `filterdialog` component. `hideSelections` is also called in the `list` controller when filters have been changed and there actually filters being applied instead of removed.

**Issues**
Fixes #5209

### CODE REVIEW

**Comment by thornbill** [comment]
@ConnorS1110 could you resolve the conflicts here? Now that 10.9 is finally out let's work on getting this in. 👍

**Comment by ConnorS1110** [comment]
@thornbill fixed the merge conflict and looks like everything is still good

**Comment by thornbill** [comment]
Sorry got the delay. I’ve been a bit busy dealing with bugs in 10.9 but I think that is finally starting to settle down. 

This would probably be a good candidate for 10.9 if you don’t mind going through the rebase process.

**Comment by ConnorS1110** [comment]
Do you mean a candidate for 10.10? @thornbill

**Comment by thornbill** [comment]
No I mean 10.9 since it is a relatively small bug fix we can get it in a patch release. You can follow the process described here to update this PR to target the release branch: https://github.com/jellyfin/jellyfin-web/pull/5680#issuecomment-2156018605

**Comment by ConnorS1110** [comment]
I don't think I've done this correctly, but I can't figure out what I did wrong. I rebased and accepted the current changes for everything.

**Comment by ConnorS1110** [comment]
Ok I think? I fixed it. I am assuming I was supposed to literally remove all the commit lines that were not mine when doing the rebase

**Comment by dmitrylyzo** [comment]
> I don't think I've done this correctly, but I can't figure out what I did wrong. I rebased and accepted the current changes for everything.

It just grabbed all commits to your branch.

If you are using Git CLI, use interactive mode (`-i`) and remove all but your commit from the "scenario".

Some GUI tools can do interactive rebasing too, but I don't use any of them.

File: src/components/filterdialog/filterdialog.js [hunk 1]
```diff
@@ -103,7 +104,8 @@ function updateFilterControls(context, options) {
 /**
      * @param instance {FilterDialog} An instance of FilterDialog
      */
-function triggerChange(instance) {
+function triggerChange (instance) {
```
Comment (thornbill) [inline src/components/filterdialog/filterdialog.js:107]:
```suggestion
function triggerChange(instance) {
```

File: src/controllers/list.js [hunk 2]
```diff
@@ -1137,8 +1138,11 @@ class ItemsView {
         return filters;
     }
 
-    setFilterStatus(hasFilters) {
+    setFilterStatus (hasFilters) {
```
Comment (thornbill) [inline src/controllers/list.js:1141]:
```suggestion
    setFilterStatus(hasFilters) {
```

**Review by thornbill — COMMENTED** [review]
Just a minor note, we are somewhat inconsistent with spacing after a function name, but we should prefer no space.

File: src/components/filterdialog/filterdialog.js (hunk 1 above)
Comment (ConnorS1110) [reply src/components/filterdialog/filterdialog.js]: Damn linter. I'm used to projects that always have a space after the function name so my linter has always been configured to do that automatically. Fixed it now.

**Review by thornbill — APPROVED** [review]
