### PR TITLE
Fix artists album lists

### LINKED ISSUE #2757: Too many albums by artist
**Describe the bug**

**System (please complete the following information):**
 - OS: Solus
 - Virtualization: Docker
 - Clients: Browser, Jellyfin media player
 - Browser: Firefox 87.0
 - Jellyfin Version: 10.7.2
 - Playback: Not important 
 - Installed Plugins: AudioDB, Fanart, MusicBrainz, OMDb, TMDb Box Sets, Trakt, YoutubeMetadata
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Click on an artist
2. See that there is every album that artist ever participated to.

**Expected behavior**

See only album by the artist.

**Logs**

**Screenshots**

Screenshot_20210423_214302

**Additional context**

I'm pretty sure the problem come from jellyfin mixing up "artist" and "albumartist".
Example of album.nfo :
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<album>
  <review />
  <outline />
  <lockdata>false</lockdata>
  <dateadded>2021-01-12 20:29:51</dateadded>
  <title>The Unauthorized Bash Brothers Experience</title>
  <year>2019</year>
  <premiered>2019-05-23</premiered>
  <releasedate>2019-05-23</releasedate>
  <runtime>26</runtime>
  <genre>Comedy</genre>
  <genre>Hip Hop</genre>
  <musicbrainzalbumid>37cb7215-e6fb-443c-95c1-421fbb9b167b</musicbrainzalbumid>
  <musicbrainzreleasegroupid>a792462c-c76d-43b3-a62d-a29ac2ff055a</musicbrainzreleasegroupid>
  <art>
    <poster>/data/music/The Lonely Island/The Lonely Island - ALBUM - 2019 - The Unauthorized Bash Brothers Experience/folder.jpg</poster>
  </art>
  <artist>HAIM</artist>
  <artist>Maya Rudolph</artist>
  <artist>Sia</artist>
  <artist>The Lonely Island</artist>
  <artist>The Unauthorized Bash Brothers Experience</artist>
  <albumartist>The Lonely Island</albumartist>
  <track>
    <position>1</position>
    <title>Jose &amp; Mark</title>
    <duration>02:25</duration>
  </track>
  <track>
    <position>2</position>
    <title>Uniform On</title>
    <duration>01:45</duration>
  </track>
  <track>
    <position>3</position>
    <title>Let’s Bash</title>
    <duration>02:23</duration>
  </track>
  <track>
    <position>4</position>
    <title>Oakland Nights</title>
    <duration>03:13</duration>
  </track>
  <track>
    <position>5</position>
    <title>Focused AF</title>
    <duration>01:55</duration>
  </track>
  <track>
    <position>6</position>
    <title>Focus on the Game</title>
    <duration>01:36</duration>
  </track>
  <track>
    <position>7</position>
    <title>Bikini Babe Workout</title>
    <duration>03:25</duration>
  </track>
  <track>
    <position>8</position>
    <title>IHOP</title>
    <duration>01:41</duration>
  </track>
  <track>
    <position>9</position>
    <title>IHOP Parking Lot</title>
    <duration>02:33</duration>
  </track>
  <track>
    <position>10</position>
    <title>Feed the Beast</title>
    <duration>02:20</duration>
  </track>
  <track>
    <position>11</position>
    <title>Daddy</title>
    <duration>02:33</duration>
  </track>
  <artistdesc>The Lonely Island is an American comedy trio, formed by Akiva Schaffer, Andy Samberg, and Jorma Taccone in Berkeley, California in 2001. They have written for and been featured in the American TV program Saturday Night Live (SNL).
The three first met in junior high. After graduating from college, they regrouped and moved to Los Angeles, where they struggled to find work and began making short films, combining absurdist comedy and occasionally music. Among the first performers to post their material on the Internet, they involved themselves with Channel 101, a non-profit monthly short film festival. Their popularity at the screenings led to unsuccessful pilot deals with Fox and Comedy Central and a writing job for the 2005 MTV Movie Awards. That show's host, Jimmy Fallon, recommended them to Lorne Michaels, the creator of Saturday Night Live.
The group was hired for SNL in 2005, with all three as writers and Samberg as a featured player. Bypassing the traditional process of pitching, they recorded their own material independently and submitted it to the program. Their second sketch to air, "Lazy Sunday", became an internet sensation, the first of many viral videos they produced while at SNL. They led their own division at the program — SNL Digital Shorts — which led to numerous viral videos, including "Motherlover", "Dick in a Box", "Jizz in My Pants", "I'm on a Boat", "Like a Boss", "I Just Had Sex", "Jack Sparrow", and "YOLO". Their musical comedic work has comprised four full studio albums: Incredibad (2009), Turtleneck &amp; Chain (2011), The Wack Album (2013), and The Unauthorized Bash Brothers Experience (2019), along with a soundtrack album for their 2016 film Popstar: Never Stop Never Stopping. The three retired from SNL in the early 2010s, but occasionally make guest appearances.
The troupe has written, directed and starred in two feature-length films, Hot Rod, released in 2007, and Popstar: Never Stop Never Stopping, co-produced by Judd Apatow and released in 2016. The group also produced the 2020 film Palm Springs, starring Samberg and Cristin Milioti.

</artistdesc>
  <label />
</album>
```

### LINKED ISSUE #3588: [10.8.0 - beta2] Incorrect display of artists album(s) and appears on. Affects all music in the library
**Describe The Bug**
Incorrect display of artists album(s) and appears on for all artists.   This has been checked with Mp3tag which shows all affected music are tagged correctly. 

**Steps To Reproduce**
1.	Navigate to your music library

2.	Choose an artist by clicking on their name or search for an artist and click on them

3.	Information falls under three headings. ‘Albums’, ‘Appears On’ and ‘More Like This’.

4.	Under the heading ‘Albums’, all music the artist appears on is listed. Even on Albums which are not the artists Albums. Only albums which the artist is the actual Album artist should be list here. 

5.	Under the Heading, ‘Appears On’, the Artists albums and singles are listed here. This should only display music where the artist features and should not include their albums. 

6.	More like this is still broken, an issue has been logged here as it is caused by a cahnge in how the Plain Folder view works since Jellyfin 10.7.0:  https://github.com/jellyfin/jellyfin/issues/5517

**Expected Behavior**
As things stand it looks like the code to display ‘Appears On’,   should be switched with the code that displays ‘Albums’. And the code that displays ‘Albums’ should exclude the ‘Album Artist’ tag from the search.  

 These issues were not in Jellyfin 10.6.x and were introduced in Jellyfin 10.7.0 and still persist in the latest Jellyfin 8 beta 2

**System (please complete the following information):**
 - Platform: Jellyfin container 
 - Browser: All and any
 - Jellyfin Version: 10.8.0 Beta 2

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
Fixes the fix from #2758 so that the "Albums" section shows albums where the artist is the AlbumArtist and the "Appears On" section shows albums where the artist is a ContributingArtist.

| Before | After |
|:-:|:-:|
| Screenshot 2022-05-11 at 10-44-49 Jellyfin | Screenshot 2022-05-11 at 10-45-55 Jellyfin |

**Issues**
Fixes #2757 (for real this time)
Fixes #3588

### CODE REVIEW

File: src/scripts/itembynamedetailpage.js [hunk 1]
```diff
@@ -275,6 +275,12 @@ function loadItems(element, item, type, query, listOptions) {
             element.querySelector('a').classList.add('hide');
         }
 
+        // If results are empty, hide the section
+        if (!result.Items?.length) {
+            element.classList.add('hide');
+            return;
+        }
+
```
Comment (dmitrylyzo) [inline src/scripts/itembynamedetailpage.js:283]: Should we also skip the block above?
Or, on the other hand, shouldn't we clear `itemsContainer.innerHTML` on reloading if the metadata has changed?

**Review by dmitrylyzo — APPROVED** [review]
