### PR TITLE
Move user settings menu to react

### LINKED ISSUE #6615: User preference -> User name is loaded late causing a display delay
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-web/issues?q=is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

As seen in the attached video (made from the demo server) the user name and "Quick connect" are delayed (~1.5 sec) hereby causing a disruption of the available links and creates a content movement among available sections.

https://github.com/user-attachments/assets/872fec60-c2ce-4036-bcaa-c65d35d2b3cc

### Reproduction Steps

1. Go to User preference (see the video)

### Expected/Actual behaviour

No delay.

### Logs

_No response_

### Server version

10.11

### Web version

10.11

### Build version

10.11

### Platform

ChromeOS

### Browser

Chrome

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
* Moves the user settings menu to react to avoid view re-rendering. Should be no visual or functional changes.

**Issues**
Fixes #6615

### CODE REVIEW

**Comment by jhparker88** [comment]
I had quick look on the dev environment and it solves the mentioned issue in #6615. 

While not caused by this PR, one think that stands out is the left alignment of the "Quick Connect" while all other sections are centered.

Screenshot 2025-03-29 015421

Screenshot 2025-03-29 015443

Screenshot 2025-03-29 015359

File: src/apps/stable/routes/user/settings/index.tsx [hunk 1]
```diff
@@ -0,0 +1,356 @@
...
+    ), [ currentUser, userId ]);
+
+    useEffect(() => {
+        if (userId) {
+            if (userId === currentUser?.Id) setUser(currentUser);
+            else setUser(users?.find(({ Id }) => userId === Id));
+        }
+    }, [ currentUser, userId, users ]);
+
+    if (!userId || !user || isQuickConnectEnabledPending) return null;
```
Comment (viown) [inline src/apps/stable/routes/user/settings/index.tsx:41]: Maybe we can return `<Loading />` here? Refreshing the page just causes it to blank for a period of time.

**Review by viown — APPROVED** [review]
