### PR TITLE
Fix ends at not always accounting for playback position

### LINKED ISSUE #6964: "Ends At" time on details page doesn't account for playback position
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-web/issues?q=is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

The ends at time on the details page doesn't account for playback position.
This means that when you click on an item in the "continue watching" section, it shows its end time as if you hadn't started watching it.

### Reproduction Steps

1. Partially watch a tv show or movie
2. Go back to the main page and note that the progress bar shows that you have partially watched it
Image
3. Click on the thumbnail and note that the "Ends At" time doesn't account for what you've already watched
Image
4. Resume watching the episode/movie and note that the "Ends At" in the player is different
Image

### Expected/Actual behaviour

I expect the "Ends At" time to account for what I've already watched and it should match the "Ends At" time in the player.

### Logs

_No response_

### Server version

10.10.7

### Web version

10.10.7 (f4b8aa0ed4)

### Build version

Release

### Platform

Linux

### Browser

All versions

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by johnnyg**
Update all "Ends At" times to use the same function which takes playback position into account.
Note that the "Ends At" time doesn't always account for playback rate however this can be addressed in another PR.

**Changes**
Update all the "Ends At" code to use `getEndsAtFromPosition`

**Issues**
Fixes #6964

### CODE REVIEW

File: src/components/mediainfo/mediainfo.js [hunk 1]
```diff
@@ -321,11 +321,10 @@ export function getMediaInfoHtml(item, options = {}) {
 
 export function getEndsAt(item) {
     if (item.MediaType === 'Video' && item.RunTimeTicks && !item.StartDate) {
-        let endDate = new Date().getTime() + (item.RunTimeTicks / 10000);
-        endDate = new Date(endDate);
-
-        const displayTime = datetime.getDisplayTime(endDate);
-        return globalize.translate('EndsAtValue', displayTime);
+        const positionTicks = item.UserData?.PlaybackPositionTicks ?? 0;
```
Comment (dmitrylyzo) [inline src/components/mediainfo/mediainfo.js]: You can omit `?? 0` since `getEndsAtFromPosition` has `|| 0`.
https://github.com/jellyfin/jellyfin-web/blob/18f3083e69e17634c52ff842e003b1b01c17fcb0/src/components/mediainfo/mediainfo.js#L335

If you want a defined value, use `|| 0` since it more portable (_legacy browsers_) and will produce the same result.

File: src/components/mediainfo/EndsAt.tsx [hunk 2]
```diff
@@ -1,28 +1,29 @@
...
         className
     );
 
-    const endTime = new Date().getTime() + (runTimeTicks / 10000);
-    const endDate = new Date(endTime);
-    const displayTime = datetime.getDisplayTime(endDate);
+    const playbackRate = 1;
+    const includeText = true;
+
+    const displayTime = mediainfo.getEndsAtFromPosition(runTimeTicks, positionTicks, playbackRate, includeText);
```
Comment (thornbill) [inline src/components/mediainfo/EndsAt.tsx]:
```suggestion
    const displayTime = mediainfo.getEndsAtFromPosition(runTimeTicks, positionTicks, 1, true);
```

File: src/components/mediainfo/mediainfo.js [hunk 3]
```diff
@@ -321,11 +321,10 @@ export function getMediaInfoHtml(item, options = {}) {
...
     if (item.MediaType === 'Video' && item.RunTimeTicks && !item.StartDate) {
-        let endDate = new Date().getTime() + (item.RunTimeTicks / 10000);
-        endDate = new Date(endDate);
-
-        const displayTime = datetime.getDisplayTime(endDate);
-        return globalize.translate('EndsAtValue', displayTime);
+        const positionTicks = item.UserData?.PlaybackPositionTicks;
+        const playbackRate = 1;
+        const includeText = true;
+        return getEndsAtFromPosition(item.RunTimeTicks, positionTicks, playbackRate, includeText);
```
Comment (thornbill) [inline src/components/mediainfo/mediainfo.js]:
```suggestion
        return getEndsAtFromPosition(item.RunTimeTicks, positionTicks, 1, true);
```

**Comment by johnnyg** [comment]
Assignments were purely for readability so happy to remove them (which I've done).
