### PR TITLE
fix endsAt time when playback speed changes

### LINKED ISSUE #2700: Playback speed does not influence displayed end time
**Describe The Bug**
Playback speed different from 1x does not influence "ends at" time.

**Steps To Reproduce**
1. Start playback of a video
2. Change playback speed
3. Ends at still shows time for 1x

**Expected Behavior**
End time should adjust to current playback speed.

**Screenshots**
playback1
playback2

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.7.5

### PR DESCRIPTION
**Pull request by HazilMohamed**
**Changes**
- Add ```playbackRate``` to ```updateTimeDisplay()``` which gets the value of current playback speed.
- The endsAt time is multiplied with reciprocal of current playback speed    

**Issues**

Fixes #2700

### CODE REVIEW

**Comment by thornbill** [comment]
It looks like this will need rebased for the expected CI tasks to run.

**Comment by HazilMohamed** [comment]
So, syncing with master works? @thornbill

**Comment by dkanada** [comment]
@HazilMohamed it would indeed be fine to rebase this against the master branch.

File: src/controllers/playback/video/index.js [hunk 1]
```diff
@@ -716,9 +716,8 @@ import { appRouter } from '../../../components/appRouter';
                     } else {
                         nowPlayingPositionSlider.value = 0;
                     }
-
-                    if (runtimeTicks && positionTicks != null && currentRuntimeTicks && !enableProgressByTimeOfDay && currentItem.RunTimeTicks && currentItem.Type !== 'Recording') {
-                        endsAtText.innerHTML = '&nbsp;&nbsp;&nbsp;&nbsp;' + mediaInfo.getEndsAtFromPosition(runtimeTicks, positionTicks, true);
+                    if (runtimeTicks && positionTicks != null && currentRuntimeTicks && !enableProgressByTimeOfDay && currentItem.RunTimeTicks && currentItem.Type !== 'Recording' && playbackRate !== null) {
+                        endsAtText.innerHTML = '&nbsp;&nbsp;&nbsp;&nbsp;' + mediaInfo.getEndsAtFromPosition(runtimeTicks, positionTicks, playbackRate, true);
```
Comment (dkanada) [inline src/controllers/playback/video/index.js:720]: If you add the newline back here the diff will be much easier to parse.

Comment (HazilMohamed) [reply src/controllers/playback/video/index.js]: Is that okay now?

File: src/controllers/playback/video/index.js [hunk 2]
```diff
@@ -716,9 +716,9 @@ import { appRouter } from '../../../components/appRouter';
                     } else {
                         nowPlayingPositionSlider.value = 0;
                     }
-
-                    if (runtimeTicks && positionTicks != null && currentRuntimeTicks && !enableProgressByTimeOfDay && currentItem.RunTimeTicks && currentItem.Type !== 'Recording') {
-                        endsAtText.innerHTML = '&nbsp;&nbsp;&nbsp;&nbsp;' + mediaInfo.getEndsAtFromPosition(runtimeTicks, positionTicks, true);
+
```
Comment (Shadowghost) [inline src/controllers/playback/video/index.js:719]:
```suggestion

```

File: src/controllers/playback/video/index.js (hunk 1 above)
Comment (dmitrylyzo) [inline src/controllers/playback/video/index.js:720]: _A rebellious line_ :sweat_smile: 

Team wants this line in place without trailing spaces - it separates the if-blocks logically and, in theory, will simplify GH diff.
In last commit, GH decided to remove it instead of just a trailing spaces. I hope the next change lands correctly.

_You are free to squash commits about this line (this suggestion and previous) with a merge commit._
```suggestion

                    if (runtimeTicks && positionTicks != null && currentRuntimeTicks && !enableProgressByTimeOfDay && currentItem.RunTimeTicks && currentItem.Type !== 'Recording' && playbackRate !== null) {
                        endsAtText.innerHTML = '&nbsp;&nbsp;&nbsp;&nbsp;' + mediaInfo.getEndsAtFromPosition(runtimeTicks, positionTicks, playbackRate, true);
```

Comment (HazilMohamed) [reply src/controllers/playback/video/index.js:720]: The thing is whenever I add a newline, one of the checks is getting failed. That's why I removed that line in the first place.

Comment (dmitrylyzo) [reply src/controllers/playback/video/index.js:720]: That check fails on trailing spaces. Some IDEs put indent automatically.

Comment (HazilMohamed) [reply src/controllers/playback/video/index.js:720]: Yes, definitely that can be a reason. The one you suggested have no trailing spaces, right?

Comment (dmitrylyzo) [reply src/controllers/playback/video/index.js:720]: Yes, it is just empty line.

**Review by dmitrylyzo — APPROVED** [review]
LGTM
There is some inconsistency with SyncPlay when changing the playback rate. This is because SyncPlay controls the playback rate itself and reverts to 1.0x not immediately.
