### PR TITLE
Various fixes for webOS 3.3

### LINKED ISSUE #306: RequireJS regression in old Chromium versions (webOS) [10.2.2 -> 10.3.0]
**Describe the bug**
`RequireJS error: TypeError: undefined is not a function. Failed modules: ` at `site.js?v=10.3.2:389`

This did not occur in the 10.2.2 version

**To Reproduce**
Try to load the web UI on an LG webOS tv v3 (and probably earlier)

So Chromium 38 and WebKit 538.2: http://webostv.developer.lge.com/discover/specifications/web-engine/

**Expected behavior**

**Logs**
`RequireJS error: TypeError: undefined is not a function. Failed modules: ` at `site.js?v=10.3.2:389`

Is the first (and only) line.

**System (please complete the following information):**
 - OS: webOS v3.x
 - Browser: WebAppManager (the "native" apps)
 - Jellyfin Version: 10.3.x

**Additional context**
Not the browser app, although that also does not work.

### PR DESCRIPTION
**Pull request by oddstr13**
**Changes**
  * Add back `Object.assign` and `fetch` polyfills.
  * remove occurances of `Promise.finally()`.
  * move functions out of if statements (strict mode)
  * make `delayedError` spit out a stack trace.

**Issues**
Fixes #306 (for webOS 3.3, not tested with webOS 2.0)

### CODE REVIEW

File: src/bower_components/alameda/alameda.js [hunk 1]
```diff
@@ -239,6 +239,7 @@ var requirejs, require, define;
         }
 
         function delayedError(e) {
+            console.log(e.stack);
```
Comment (thornbill) [inline src/bower_components/alameda/alameda.js]: I'm guessing this was just added for debugging? Should probably remove it so we aren't modifying 3rd party libs.

File: src/components/appRouter.js [hunk 2]
```diff
@@ -343,7 +342,6 @@ define(['loading', 'globalize', 'events', 'viewManager', 'layoutManager', 'skinM
                 hashbang: options.hashbang !== false,
                 enableHistory: enableHistory()
             });
-        }).finally(function () {
```
Comment (thornbill) [inline src/components/appRouter.js]: This may end up in the loading indicator not being hidden if an error occurs. We may want to do something like `.catch().then(function() { ... })` to emulate the behavior of `.finally()`.

File: src/controllers/loginpage.js [hunk 3]
```diff
@@ -156,8 +156,6 @@ define(["apphost", "appSettings", "dom", "connectionManager", "loading", "cardSt
                     view.querySelector("#txtManualName").value = "";
                     showManualForm(view, false, false);
                 }
-
-            }).finally(function () {
```
Comment (thornbill) [inline src/controllers/loginpage.js]: Same as above.

File: src/bower_components/alameda/alameda.js (hunk 1 above)
Comment (oddstr13) [reply src/bower_components/alameda/alameda.js]: I left this one in intentionally, as without it you don't get the source of errors, just a cryptic line of text (see #306 for example)

File: src/components/appRouter.js (hunk 2 above)
Comment (oddstr13) [reply src/components/appRouter.js]: Wasn't entirely sure of how to handle the lack of `.finally()`
