### PR TITLE
Show nested chapters in bookplayer TOC

### LINKED ISSUE #4486: Book (epub) do not show sub-entries in the table of contents
**Describe The Bug**
A book in the ePub format can have a hierarchical structure of chapters with sub-chapters etc. Those sub-chapters do not appear in the table of contents view in Jellyfin. Only the top-level chapter's get displayed.
In the screenshot section are some screenshots of an example file to illustrate the problem (Jellyfin vs Calibre). But really, any chapter names and chapter-structure has those problems. I could've move some chapters to the top level and added sub-chapters to them, too, e.g.:
```
Cover
Made in Abyss 08
- Chapter 01
- Chapter 02
Side Story
- Chapter 01
- Chapter 02
```

**Steps To Reproduce**
1. Go to your book library.
2. Click on a book to open it. It has to be an ePub file with sub-chapters!
3. Click on the button for the table of contents.

**Expected Behavior**
Show a list of all chapters. 

**Screenshots**
The problem:
image
How it should look like (image from calibre):
image

**System (please complete the following information):**
 - Platform: Fedora Linux
 - Jellyfin + Jellyfin Web Version: 10.8.9

### PR DESCRIPTION
**Pull request by vincent**
**Changes**
This PR modify the bookplayer TOC dialog to show nested chapters.

**Issues**
Fixes #4486

### CODE REVIEW

**Comment by vincent** [comment]
Screenshot of the current proposal

image

**Review by carif — APPROVED** [review]
Looks good to me. :+1: 
At least with my small test library, I could not identify any problems.

File: src/plugins/bookPlayer/tableOfContents.js [hunk 1]
```diff
@@ -51,6 +51,25 @@ export default class TableOfContents {
         });
     }
 
+    chapterTocItem(book, chapter) {
+        let itemHtml = '<li>';
+
+        // remove parent directory reference from href to fix certain books
+        const link = chapter.href.startsWith('../') ? chapter.href.slice(3) : chapter.href;
+        itemHtml += `<a href="${book.path.directory + link}">${chapter.label}</a>`;
```
Comment (thornbill) [inline src/plugins/bookPlayer/tableOfContents.js:59]: There should be html escaping here to prevent xss.

You will need to add the import `import escapeHTML from 'escape-html';` and then escape the link and label:

```suggestion
        itemHtml += `<a href="${escapeHTML(book.path.directory + link)}">${escapeHTML(chapter.label)}</a>`;
```

**Review by thornbill — CHANGES_REQUESTED** [review]
Looks good and works in my testing! I just had a quick comment about a potential vulnerability in this code that was pre-existing. :slightly_smiling_face:

**Review by thornbill — APPROVED** [review]
