### PR TITLE
Show a different icon when the player is paused

### LINKED ISSUE #3901: Audio visualizer animation continues when music is paused
**Describe The Bug**

When listening to music on Jellyfin, the queue page replaces the cover image of the playing track with a GIF.
However, when the music is paused, the animation continues.

image
> On the side, this GIF could probably be replaced with an SVG.

**Steps To Reproduce**

1. Go to a music library
2. Click on the play button for an album
3. Click on the bar at the bottom to get taken to `/queue`
4. Pause the music

**Expected Behavior**

I would expect one of the following:
1. The animation pauses.
2. The image is replaced with a pause icon. ⏸️

I think number 2 would be better and easier to implement.
You can probably just use the pause Material Icon ([here)](https://fonts.google.com/icons?selected=Material+Icons&icon.query=pause) since that's already in Jellyfin anyway.

**Logs**

N/A

**Screenshots**

image
> Just pretend you can see the GIF still moving. ^-^'

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox / [Jellyfin Media Player](https://github.com/jellyfin/jellyfin-media-player)
 - Jellyfin Version: 10.7.6

**Additional Context**

This is just a minor UX concern, it can throw a user off when part of the UI suggests that music should be playing when it's not.

---

Just re-opening: #2792

### PR DESCRIPTION
**Pull request by vincent**
**Changes**
This PR shows a still version of the playing icon in the playlist, when the player is paused.

**Issues**
Fixes #3901

### CODE REVIEW

File: src/components/remotecontrol/remotecontrol.js [hunk 1]
```diff
@@ -598,6 +599,7 @@ export default function () {
 
     function onPlayPauseStateChanged() {
         updatePlayPauseState(this.paused(), true);
+        onPlaylistUpdate();
```
Comment (dmitrylyzo) [inline src/components/remotecontrol/remotecontrol.js:602]: IMO, updating the entire playlist is too much.
What if query `.playlistIndexIndicatorImage` and toggle the paused class?

File: src/assets/img/equalizer-paused.gif
Comment (thornbill) [inline src/assets/img/equalizer-paused.gif:1]: If this is not animated, a different format would probably be better than gif.

**Review by thornbill — APPROVED** [review]
