### PR TITLE
Fix the overlap in iOS music view and the hidden nowPlayingBar

### LINKED ISSUE #1602: iOS music view overflows with long album titles.
64312B6B-5B79-49EB-B064-1FFA2516C246
Longer album titles cause overflow on the new mobile music view in 10.6, at least on iOS, iPhone 8

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- Fix the overlap in iOS music view.
- Fix the issue that nowPlayingBar is still hidden after exiting the music control pannel.

Before: 

After: 100%  125%: 

**Issues**
Fixes #1602 #1931

### CODE REVIEW

**Review by MrTimscampi — APPROVED** [review]

**Review by Camc314 — APPROVED** [review]

File: src/components/nowPlayingBar/nowPlayingBar.js [hunk 1]
```diff
@@ -660,7 +660,7 @@ import { appRouter } from '../appRouter';
         console.debug('nowplaying event: ' + event.type);
         const player = this;
 
-        if (!state.NowPlayingItem || layoutManager.tv || !state.IsFullscreen) {
+        if (!state.NowPlayingItem || layoutManager.tv) {
```
Comment (thornbill) [inline src/components/nowPlayingBar/nowPlayingBar.js:663]: This change reverts https://github.com/jellyfin/jellyfin-web/pull/2028. Should we handle that differently somehow?

Comment (MrTimscampi) [reply src/components/nowPlayingBar/nowPlayingBar.js:663]: Probably, but the main issue is that it's using the "music" player to play theme songs, which is of course attached to all the audio playing stuff in Jellyfin (playlist, controls, etc).

So short of reworking theme songs, I don't see a good way to handle this :/

Comment (dmitrylyzo) [reply src/components/nowPlayingBar/nowPlayingBar.js:663]: `state.IsFullscreen` is only set when playback starts. Probably should be updated in this function https://github.com/jellyfin/jellyfin-web/blob/e56414ebe8876f6ba23a667ddbdc6b0dc8264678/src/components/playback/playbackmanager.js#L1932

Quick fix.
```suggestion
        if (!state.NowPlayingItem || layoutManager.tv || state.IsFullscreen === false) {
```

Comment (nyanmisaka) [reply src/components/nowPlayingBar/nowPlayingBar.js:663]: Nice! It works.

**Review by thornbill — APPROVED** [review]
