### PR TITLE
Fix playing next episode when autoplay is disabled

### LINKED ISSUE #2596: Doesn't play next episode when clicking >|
I noticed when 'Play next episode automatically' is not enabled in profile settings this button
image

doesn't do anything when clicked. Making it impossible to skip currently played episode to the next one.

present on  10.7.x

### LINKED ISSUE #5382: [Issue]: Users with "Play next episode automatically" unchecked cannot skip to previous/next episode and won't be presented 'next video info popup' at end of playback
### Please describe your bug

If a user doesn't have "Play next episode automatically" selected in the user's playback settings, they are unable to use the "Skip to Previous" and "Skip to next" buttons and they're not shown the 'next video info' popup at end of episodes even though there are more episodes in that show's season.

The workaround for this is to check the "Play next episode automatically" setting under Playback in the user's settings and the logging out and logging in the user again (the setting seem cached on login). 

I'm suspecting this is not supposed to happen, as a user (IMO) ought to be able to at least flip back/forth through episodes even though they don't have "Play next episode automatically". Regarding the 'next video info' popup I guess it makes _somewhat_ more sense, but even that I think a better behavior is to not block the next episode popup even though Play next episode automatically is deselected.

### Reproduction Steps

1. Make sure "Play next episode automatically" is deselected for a user's playback settings and save settings. Bonus if 'show next video info' is selected. Logout and login again for this change to take effect. 
2. Play any series episode that has a preceding or succeeding episode
3. In web player and Jellyfin Media Player buttons to skip to previous/next episode will do nothing. On Android Jellyfin client at least "skip to next episode" button will be grayed out. At end of episode, "Next video info" popup will not be displayed.
4. Enable "Play next episode automatically" and save settings. Logout and login again for change to take effect for current session. 
5. Skipping episodes and "Next video info" popup will now work as expected

### Jellyfin Version

10.8.13

### if other:

_No response_

### Environment

```markdown
- OS: Windows 11 (Jellyfin server), Windows 11 (client), Android (client)
- Clients: Web player, Jellyfin Media Player, Android player all confirmed having this issue.
- Browser: Chrome and Firefox latest versions as of writing both have this issue with web player.
- FFmpeg Version: ffmpeg version 2022-06-20-git-56419428a8-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
- Playback Method: Direct Play, Direct Stream (unsupported audio codec) both exhibit this behavior
- Reverse Proxy: Yes (Apache 2.4 reverse proxying ext_ip:8920 to int_ip:8920 (valid TLS cert on Jellyfin server and HTTPS enabled in Network) 
- Base URL: N/A (not set)
- Networking: Jellyfin server is on host network (standard Windows IPv4 LAN address)
- Storage: Media is located on a Samba share
```

### Jellyfin logs

```shell
---start jellyfin server log + 10 lines before and after same operation as above---
[2024-04-10 20:32:45.798 +02:00] [INF] [248] Jellyfin.Api.Helpers.TranscodingJobHelper: Stopping ffmpeg process with q command for "C:\Users\mahriman\AppData\Local\Jellyfin\transcodes\9c4243c6fdeb2f7f31ef504eddf650a9.m3u8"
[2024-04-10 20:32:45.806 +02:00] [INF] [109] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI0LjB8MTcxMjc3MTE0ODE5MQ11-3b57de27d3c74bd8948bec7df2c0d9af-2031e2c34bee71d062043747c4cb3c17
[2024-04-10 20:32:45.807 +02:00] [INF] [109] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 04/10/2024 20:32:45
[2024-04-10 20:32:45.807 +02:00] [INF] [109] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2024-04-10 20:32:45.808 +02:00] [INF] [220] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2024-04-10 20:32:45.885 +02:00] [INF] [248] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2024-04-10 20:32:45.886 +02:00] [INF] [248] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-04-10 20:32:45.887 +02:00] [INF] [248] Jellyfin.Api.Helpers.TranscodingJobHelper: "C:\tools\ffmpeg\bin\ffmpeg.exe" "-analyzeduration 200M -ss 00:09:18.558 -fflags +genpts  -i file:\"M:\unrared-mergerfs\TV\After.Midnight.2024\After.Midnight.2024.S01.1080p.WEB.h264-EDITH\After.Midnight.2024.2024.01.16.Whitney.Cummings.1080p.WEB.h264-EDITH\After.Midnight.2024.2024.01.16.Whitney.Cummings.1080p.WEB.h264-EDITH.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 93 -hls_segment_filename \"C:\Users\mahriman\AppData\Local\Jellyfin\transcodes\9c4243c6fdeb2f7f31ef504eddf650a9%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"C:\Users\mahriman\AppData\Local\Jellyfin\transcodes\9c4243c6fdeb2f7f31ef504eddf650a9.m3u8\""
[2024-04-10 20:32:46.334 +02:00] [INF] [89] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI0LjB8MTcxMjc3MTE0ODE5MQ11-3b57de27d3c74bd8948bec7df2c0d9af-2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:32:50.605 +02:00] [INF] [197] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2024-04-10 20:33:05.810 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "192.168.1.1"
[2024-04-10 20:33:05.811 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:05.811 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "3b57de27d3c74bd8948bec7df2c0d9af"
[2024-04-10 20:33:05.812 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 1
[2024-04-10 20:33:05.812 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = "2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:05.813 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "3b57de27d3c74bd8948bec7df2c0d9af"
[2024-04-10 20:33:05.813 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "Transcode (v:direct a:direct)"
[2024-04-10 20:33:05.814 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Jellyfin Web"
[2024-04-10 20:33:05.814 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "Firefox"
[2024-04-10 20:33:05.815 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "After Midnight - s01e01 - Whitney Cummings, Aparna Nancherla, Kurt Braunohler"
[2024-04-10 20:33:05.815 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:05.815 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "Episode"
[2024-04-10 20:33:05.816 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : All matches, playback registered
[2024-04-10 20:33:05.816 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback tracker found, adding playback info : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI0LjB8MTcxMjc3MTE0ODE5MQ11-3b57de27d3c74bd8948bec7df2c0d9af-2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:05.817 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2024-04-10 20:33:05.819 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[2024-04-10 20:33:11.393 +02:00] [INF] [54] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
[2024-04-10 20:33:11.394 +02:00] [INF] [54] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ItemAddedScheduledTask"
[2024-04-10 20:33:11.394 +02:00] [INF] [351] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Webhook Item Added Notifier"
[2024-04-10 20:33:11.395 +02:00] [DBG] [351] Jellyfin.Plugin.Webhook.Notifiers.ItemAddedNotifier.ItemAddedManager: ProcessItemsAsync
[2024-04-10 20:33:11.395 +02:00] [INF] [351] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2024-04-10 20:33:11.396 +02:00] [INF] [351] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2024-04-10 20:33:12.365 +02:00] [INF] [301] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI0LjB8MTcxMjc3MTE0ODE5MQ11-3b57de27d3c74bd8948bec7df2c0d9af-2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:32.390 +02:00] [INF] [54] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTI0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTI0LjB8MTcxMjc3MTE0ODE5MQ11-3b57de27d3c74bd8948bec7df2c0d9af-2031e2c34bee71d062043747c4cb3c17"
[2024-04-10 20:33:41.407 +02:00] [INF] [334] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
[2024-04-10 20:33:41.407 +02:00] [INF] [334] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ItemAddedScheduledTask"
---end jellyfin server log + 10 lines before and after same operation as above---
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

jellyfin-issue-dev-tools-console-output

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ConnorS1110**
This issue was caused by us doing the user flag check during playlist creation, rather than when an episode has ended. Fixing this will simultaneously fix the player automatically playing the next episode with the flag `Play next episode automatically` disabled and allow proper usage of the skip to next/previous buttons for people with this flag disabled.

**Changes**
Moved checking the user setting flag from where the playlist is loaded to where we attempt to load the next episode after playback has been stopped (ie reaching the end of an episode).

**Issues**
Fixes #5382 
Fixes #2596

### CODE REVIEW

File: src/components/playback/playbackmanager.js [hunk 1]
```diff
@@ -1945,8 +1945,8 @@ class PlaybackManager {
                 promise = new Promise(function (resolve, reject) {
                     const apiClient = ServerConnections.getApiClient(firstItem.ServerId);
 
-                    apiClient.getCurrentUser().then(function (user) {
-                        if (!user.Configuration.EnableNextEpisodeAutoPlay || !firstItem.SeriesId) {
+                    apiClient.getCurrentUser().then(function () {
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1948]: I think there is no need for `getCurrentUser` now (called to retrieve the user's configuration/policy.)

Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js:1948]: Yeah you're right. Just followed the pattern I saw used elsewhere. It has been updated.

Comment (dmitrylyzo) [reply src/components/playback/playbackmanager.js:1948]: You removed wrong `getCurrentUser`.

Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Whoops I misunderstood. Think it's actually fixed this time.

**Review by dmitrylyzo — APPROVED** [review]
LGTM.
And thank you for contribution.

File: src/components/playback/playbackmanager.js [hunk 2]
```diff
@@ -3324,7 +3322,13 @@ class PlaybackManager {
             if (errorOccurred) {
                 showPlaybackInfoErrorMessage(self, 'PlaybackError' + displayErrorCode);
             } else if (nextItem) {
-                self.nextTrack();
+                const apiClient = ServerConnections.getApiClient(nextItem.item.ServerId);
+
+                apiClient.getCurrentUser().then(function (user) {
+                    if (user.Configuration.EnableNextEpisodeAutoPlay) {
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:3328]: Oh. Add here a check: if `nextItem.Type` is not a video, play next. Currently, music playback is broken.

**Review by dmitrylyzo — CHANGES_REQUESTED** [review]

File: src/components/playback/playbackmanager.js (hunk 2 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Fixed this. Had a sonarcloud failure as well so I refactored the function to prevent this failure. Hopefully makes it more readable now as well. I tested with movies, shows, music, photos, and home videos and it seems like there is no regression. Maybe give it a light once over to be sure.

**Comment by dmitrylyzo** [comment]
The commit has now become complex/non-atomic.
I would just ignore SonarCloud - it was not relevant to your changes.
At the very least, the refactoring should be done in a separate commit.

File: src/components/playback/playbackmanager.js [hunk 3]
```diff
@@ -3325,7 +3341,7 @@ class PlaybackManager {
                 const apiClient = ServerConnections.getApiClient(nextItem.item.ServerId);
 
                 apiClient.getCurrentUser().then(function (user) {
-                    if (user.Configuration.EnableNextEpisodeAutoPlay) {
+                    if (user.Configuration.EnableNextEpisodeAutoPlay || nextMediaType !== MediaType.Video) {
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:3344]: Move this change (`nextMediaType`) + SDK import to the first commit.

File: src/components/playback/playbackmanager.js [hunk 4]
```diff
@@ -1789,42 +1790,73 @@ class PlaybackManager {
...
+                return nonItemTypePromise;
+            }
+
+            switch (firstItem.Type) {
+                case 'Program':
+                    return getItemsForPlayback(serverId, { Ids: firstItem.ChannelId });
+                case 'Playlist':
+                    return getItemsForPlayback(serverId, { ParentId: firstItem.Id, SortBy: options.shuffle ? 'Random' : null });
+                case 'MusicArtist':
+                    return getItemsForPlayback(serverId, mergePlaybackQueries({ ArtistIds: firstItem.Id, Filters: 'IsNotFolder', Recursive: true, SortBy: options.shuffle ? 'Random' : 'SortName', MediaTypes: 'Audio' }, queryOptions));
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1833]: I would keep the old formatting so there are fewer changes.
```suggestion
                    return getItemsForPlayback(serverId, mergePlaybackQueries({
                        ArtistIds: firstItem.Id,
                        Filters: 'IsNotFolder',
                        Recursive: true,
                        SortBy: options.shuffle ? 'Random' : 'SortName',
                        MediaTypes: 'Audio'
                    }, queryOptions));
```

File: src/components/playback/playbackmanager.js [hunk 5]
```diff
@@ -1933,58 +1896,109 @@ class PlaybackManager {
...
+                    return true;
+                }
+
+                return false;
+            });
+            if (episodesResult.Items.length === 0) {
+                if (isSeries) {
+                    episodesResult.Items = originalResults;
+                } else {
+                    episodesResult.Items = originalResults.filter(function (e_1) {
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1939]: Is it necessary to rename `e`?

**Review by dmitrylyzo — COMMENTED** [review]
Refactoring changes require more attention, i.e. more time to review.

File: src/components/playback/playbackmanager.js (hunk 5 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Not sure how this got changed... Reverted it back to just `e`

File: src/components/playback/playbackmanager.js (hunk 4 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: I am assuming by this you are referring to the line spacing for the params for each `getItemsForPlayback` function call in the switch block. I have updated that so it matches the previous formatting.

If you mean going back to the if/else-if chain, I think I would be curious to hear more of the logic behind why you feel that should change back? I'll still change it if you have strong opinions about it, but to me having the switch makes more sense since all but 3 conditions involved checking the exact same field. If my first statement is what you were asking for, disregard this then

**Review by dmitrylyzo — COMMENTED** [review]
The formatting suggestions are just nitpicking. I'm not sure we have a strict code style for such cases. :sweat_smile:

File: src/components/playback/playbackmanager.js [hunk 6]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
             });
         }
 
-        function translateItemsForPlayback(items, options) {
+        async function translateItemsForPlayback(items, options) {
             if (!items.length) return Promise.resolve([]);
```
[the remark this answers is not in the document]
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js [hunk 7]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
...
+            const serverId = firstItem.ServerId;
+            const queryOptions = options.queryOptions || {};
+
+            const promise = getPlaybackPromise(firstItem, serverId, options, queryOptions, items);
+
+            if (promise) {
+                const result = await promise;
+                return result ? result.Items : items;
+            } else {
+                return Promise.resolve(items);
```
[the remark this answers is not in the document]
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js [hunk 8]
```diff
@@ -1933,58 +1913,109 @@ class PlaybackManager {
...
+            const episodesResult = await apiClient.getEpisodes(firstItem.SeriesId || firstItem.Id, {
+                IsVirtualUnaired: false,
+                IsMissing: false,
+                UserId: apiClient.getCurrentUserId(),
+                Fields: ['Chapters', 'Trickplay']
+            });
+            const originalResults = episodesResult.Items;
+            const isSeries = firstItem.Type === 'Series';
+            let foundItem = false;
+            episodesResult.Items = episodesResult.Items.filter(function (e) {
```
[the remark this answers is not in the document]
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js [hunk 9]
```diff
@@ -1933,58 +1913,109 @@ class PlaybackManager {
...
+                }
+
+                if (!e.UserData.Played && (isSeries || e.SeasonId === firstItem.Id)) {
+                    foundItem = true;
+                    return true;
+                }
+
+                return false;
+            });
+            if (episodesResult.Items.length === 0) {
```
[the remark this answers is not in the document]
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js [hunk 10]
```diff
@@ -1933,58 +1913,109 @@ class PlaybackManager {
...
-                            episodesResult.TotalRecordCount = episodesResult.Items.length;
-                            resolve(episodesResult);
-                        }, reject);
+                        return false;
                     });
-                });
+                }
             }
+            episodesResult.TotalRecordCount = episodesResult.Items.length;
+            return episodesResult;
```
[the remark this answers is not in the document]
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js [hunk 11]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
...
                 });
             }
+        }
 
-            const firstItem = items[0];
-            let promise;
-
-            const serverId = firstItem.ServerId;
+        function getPlaybackPromise(firstItem, serverId, options, queryOptions, items) {
+            const nonItemTypePromise = getNonItemTypePromise(firstItem, serverId, options, queryOptions);
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1822]: I was afraid the splitting would cause problems.
Currently, when you start a series/season, it falls into [`IsFolder`](https://github.com/jellyfin/jellyfin-web/blob/588da3ce95a851a3ada5ba812d15c36d039dbc24/src/components/playback/playbackmanager.js#L1909-L1925) branch (series/season is a folder, but with a corresponding type) and doesn't reach [`Series/Season`](https://github.com/jellyfin/jellyfin-web/blob/588da3ce95a851a3ada5ba812d15c36d039dbc24/src/components/playback/playbackmanager.js#L1865-L1868).

Moving the `getNonItemTypePromise` call after `switch` would fix this, but I'm not sure it wouldn't cause another problem.

Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js:1822]: What if I added additional checks on the `isFolder` if statement that also checks it doesn't have type `Series` or `Season`

Comment (dmitrylyzo) [reply src/components/playback/playbackmanager.js:1822]: > What if I added additional checks on the `isFolder` if statement that also checks it doesn't have type `Series` or `Season`

While this would solve the problem, it would make the logic more complex and the code less maintainable. _I'm not saying the current code of web doesn't look like spaghetti._ 😅

I think we should consider the "IsFolder" if statement as a fallback. In this case, moving the "non-type" promise getter after the "typed" block makes more sense.

In fact, we need to test from stricter cases to more general cases.

Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Alright I swapped the order and it seems like everything works. Tried testing with movies/season/series playing an individual episode along with playing a folder. Worked with photo slideshows as well. Just double check I didn't miss anything.

File: src/components/playback/playbackmanager.js [hunk 12]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
...
                 });
             }
+        }
 
-            const firstItem = items[0];
-            let promise;
-
-            const serverId = firstItem.ServerId;
+        function getPlaybackPromise(firstItem, serverId, options, queryOptions, items) {
+            console.log('firstItem:', firstItem);
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1823]:
```suggestion
```

File: src/components/playback/playbackmanager.js [hunk 13]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
...
+                case 'Season':
+                    return getSeriesOrSeasonPlaybackPromise(firstItem);
+                case 'Episode':
+                    return getEpisodePlaybackPromise(firstItem, options, items);
+            }
+
+            const nonItemTypePromise = getNonItemTypePromise(firstItem, serverId, options, queryOptions);
+            if (nonItemTypePromise) {
+                return nonItemTypePromise;
+            }
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1871]:
```suggestion
            return getNonItemTypePromise(firstItem, serverId, options, queryOptions);
```

File: src/components/playback/playbackmanager.js [hunk 14]
```diff
@@ -1789,42 +1790,90 @@ class PlaybackManager {
...
-                promise = getItemsForPlayback(serverId, mergePlaybackQueries({
-                    ArtistIds: firstItem.Id,
-                    Filters: 'IsNotFolder',
-                    Recursive: true,
-                    SortBy: options.shuffle ? 'Random' : 'SortName',
-                    MediaTypes: 'Audio'
-                }, queryOptions));
-            } else if (firstItem.MediaType === 'Photo') {
-                promise = getItemsForPlayback(serverId, mergePlaybackQueries({
+        function getNonItemTypePromise (firstItem, serverId, options, queryOptions) {
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1874]:
```suggestion
        function getNonItemTypePromise(firstItem, serverId, options, queryOptions) {
```

File: src/components/playback/playbackmanager.js [hunk 15]
```diff
@@ -1933,58 +1913,113 @@ class PlaybackManager {
...
                     Recursive: true,
                     // These are pre-sorted
                     SortBy: sortBy,
                     MediaTypes: 'Audio,Video'
                 }, queryOptions));
-            } else if (firstItem.Type === 'Episode' && items.length === 1 && getPlayer(firstItem, options).supportsProgress !== false) {
-                promise = new Promise(function (resolve, reject) {
-                    const apiClient = ServerConnections.getApiClient(firstItem.ServerId);
+            }
+        }
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1926]:
```suggestion
            }

            return null;
        }
```

Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done (I think I put this in the right spot)

File: src/components/playback/playbackmanager.js (hunk 14 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

File: src/components/playback/playbackmanager.js (hunk 13 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js]: Done

**Review by dmitrylyzo — APPROVED** [review]

**Comment by dmitrylyzo** [comment]
Little note:
You must refresh the web client for the changes to take effect.
`Play next episode automatically` is stored in the user configuration, which is cached by ApiClient, but the cache is not updated when the configuration is sent to the server.
We could fix this in ApiClient, but it is frozen/archived. So it is better to just migrate the playback settings to the new SDK (_not in this PR_).

File: src/components/playback/playbackmanager.js [hunk 16]
```diff
@@ -1922,58 +1908,115 @@ class PlaybackManager {
...
-                                return false;
-                            });
-                            episodesResult.TotalRecordCount = episodesResult.Items.length;
-                            resolve(episodesResult);
-                        }, reject);
+                        return false;
                     });
-                });
+                }
             }
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:1968]: These changes should be reverted because they revert https://github.com/jellyfin/jellyfin-web/pull/5415
_Merge conflicts were incorrectly resolved._

**Review by dmitrylyzo — CHANGES_REQUESTED** [review]

File: src/components/playback/playbackmanager.js (hunk 16 above)
Comment (ConnorS1110) [reply src/components/playback/playbackmanager.js:1959]: I updated the refactor to include the new changes. I believe it brings it back in parity with #5415

**Review by dmitrylyzo — APPROVED** [review]
