### PR TITLE
Fix slider step

### LINKED ISSUE #4753: LG WebOS Subtitle offset jumps by 0.6s
**Describe The Bug**
When on LG WebOS and changing subtitle offset, it jumps in steps of 0.6s making it hard to accurately select a good offset.  

**Steps To Reproduce**

1. Start media with subtitles
2. Click on the cogwheel (Settings)
3. Click on to 'Subtitle Offset'
4. Change offset
5. See offset jump by 0.6s

**Expected Behavior**

It's expected to jump in increments of 0.1s.

**System (please complete the following information):**
 - Platform: LG WebOS
 - Jellyfin Version: 10.8.10

### PR DESCRIPTION
**Pull request by dmitrylyzo**
**Changes**
Use the value of the `step` attribute if no keyboard steps are specified.

**Issues**
Fixes #4753

_Requires manual backporting (indentation change in the master)._

### CODE REVIEW

File: src/elements/emby-slider/emby-slider.js [hunk 1]
```diff
@@ -20,6 +20,27 @@ import '../emby-input/emby-input';
...
+            return step;
+        }
+
+        step = parseFloat(range.step);
+
+        if (step > 0) {
+            return step;
+        }
+
+        return 1;
```
Comment (thornbill) [inline src/elements/emby-slider/emby-slider.js:41]: What do you think about this?

```suggestion
        return Math.max(step, 1);
```

Comment (dmitrylyzo) [reply src/elements/emby-slider/emby-slider.js:41]: `parseFloat(range.step)` returns `NaN` for `'auto'` or an invalid value. `Math.max` returns `NaN` in this case.

**Review by thornbill — APPROVED** [review]
