### PR TITLE
Fix some issues with details page and small redesign

### LINKED ISSUE #928: Detail page - Align title with other content during loading
During the loading of the detail page there is a gap on the left side of the title.
It should be aligned to the other content of the page.

image
image

https://imgur.com/otXitb1

### LINKED ISSUE #1033: Mismatched backdrops on item details screen
When multiple backdrops are downloaded onto the server for a single video item and the server is configured to cycle through them only the bottom half of the item details screen (the more opaque part) cycles. They then become mismatched.

intended: they both cycle through the same images at the same time.

### LINKED ISSUE #1233: Add a way to prevent "content jumping" on item details page
Hi all.

**Describe the bug**

While loading the details page,  elements are not loaded and displayed at the same time, resulting in an unpleasant visual effect.

I know that some elements are lazily loaded and that placeholders are used, but I don't know if it's enough because some elements have variable dimensions.

I guess you are aware of the problem, but I recorded a small sequence for demonstration: https://streamable.com/7meta7

Actors are jumping because video/audio/subtitles are rendered lately. It's even more noticeable for the music albums because for a few milliseconds, the colored suggested albums are visible before being replaced by the track list.

For comparison, I recorded a similar sequence on Plex: https://streamable.com/uugpkh

As I'm not familiar with the codebase,I don't know if this is because the client needs to query the metadata from the server, or if it's because the content is dynamically generated in JS.

What do you think would be a good solution to avoid content jumping? Should we wait until everything is ready before displaying the content with a fade-in effect?

**System (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 76
 - Jellyfin Version: `master` (5c18bb40bca555d6a126962fe9a002d3118c8245)

**Attachments:**
- [examples.zip](https://github.com/jellyfin/jellyfin-web/files/4635547/examples.zip)

### LINKED ISSUE #1385: Bad formating for long titles
**Describe the bug**
Long titles don't word wrap and will shove button to the right (often off screen). 

**Screenshots**
Screenshot_2020-06-08 Jellyfin
Screenshot_2020-06-08 Jellyfin
Screenshot_2020-06-08 Jellyfin(2)

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 77.0.1
 - Jellyfin Version: 10.5.5

### LINKED ISSUE #1418: Too long movie titles appear to break the UI
**Describe the bug**
I've come to notice way too long movies titles break the UI.

**To Reproduce**
1. Add a movie with a long title such as Jim & Andy: The Great Beyond- Featuring a Very Special, Contractually Obligated Mention of Tony Clifton
2. Navigate to the movie's item details page.

**Expected behavior**
There is an example picture of the UI when the title is shorter. I would suggest putting the overflow below the title or having dynamic sizing of the div that holds the title.
It appears the item also holds the text-overflow:ellipsis, which doesn't appear to be working.

**Screenshots**
I've uploaded a picture of a movie where the title is short enough and one where the title is too long.
https://imgur.com/gallery/IV0hy0d

**System (please complete the following information):**
 - OS: [Docker in Synology]
 - Browser: [Firefox, Chrome]
 - Jellyfin Version: [e.g. 10.5.5]

**Predicted Solution**
It can be fixed by giving detailPagePrimaryContainer a fixed height, such as 100px.
https://imgur.com/gallery/kynmqP2

I can make a PR for this, given it's approval by the devs. It would be the first time I help in this project, so if there is something else, like adding myself to the contributors, etc that needs to be done first, feel free to let me know.

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

**Issues**

Fixes #1033
Fixes #1233 
Fixes #928
Fixes #1385 
Fixes #1418

### CODE REVIEW

**Comment by dkanada** [comment]
Did you replace shuffle with delete on the mobile view? Also, didn't we decide to remove trailers or something because it's not quite as important.

**Comment by MrTimscampi** [comment]
> Did you replace shuffle with delete on the mobile view? Also, didn't we decide to remove trailers or something because it's not quite as important.

I didn't, it's just that one screen is for a movie and the other is a TV show, hence the difference in buttons :)

I can try moving the trailer button to the context menu, like I did for the Delete button.

**Comment by dkanada** [comment]
Ah, I see that now, sounds good.

**Comment by hamburglar2160** [comment]
I'm not a fan of the big blue play button and its positioning. I would draw from UX/UI references here and either 
1. replace the existing trailer button with a play button or 
2. strip away the circle background and place the play logo on the bottom left or right of the thumbnail, while making all of that image clickable to play.

Random nitpick here but can we get the "1080P" replaced with "1080p?"

**Comment by dkanada** [comment]
I'm held up on the FAB at the top right, I don't think it works with the centered elements. Plex makes it look good because their title and such are left centered but our layout is different. If you really hate the translucent button over the image, I'd say we should mirror the streaming sites and have a full width button somewhere near the top.

**Comment by ferferga** [comment]
What's left for this PR?

**Comment by MrTimscampi** [comment]
Still some changes on the mobile layout that I need to make.

**Comment by Nickbert7** [comment]
Would it be possible as a part of this PR to add Blurhash for the posters/thumbs/backgrounds on the item detail page?

**Comment by ferferga** [comment]
@Nickbert7 It's already done. What was needed was to move those images to the card component, which was already done here before blurhash was added.

(I asked myself the same question too and planned to do it myself, then heard that this PR already solved that)

**Comment by Nickbert7** [comment]
Oh, that are perfectly good news😅
I just had a look into the nightly demo if my build was just to old, but there was the same behavior so I thought it would be a good idea to ask here about it😁

**Comment by ferferga** [comment]
@Nickbert7 Do note that people blurhashes doesn't work because a server-side bug which probably will make its way into 10.6.0, so until 10.6.x or 10.7 people will gracefully fallback to the old animations.

jellyfin/jellyfin#3230

**Comment by Nickbert7** [comment]
I already saw that corresponding PR, but thanks for the notice.
To be honest for me the most important places are the home screen, the lists and the part of the detail page which is directly loading into view. As for the people I have to scroll down, this is not an "urgent" issue for me, but nice that there is also a solution for.

Btw: I love the blurhash feature and the new image loader❤

**Comment by ferferga** [comment]
@Nickbert7 Thank you! ❤

Not to forget the inmense amount of work @MrTimscampi did as well for the unloader and intersection observer, web it's slick right now in a big part thanks to him :).

File: src/components/groupedcards.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ define(['dom', 'appRouter', 'connectionManager'], function (dom, appRouter, conn
                     return void appRouter.showItem(items[0]);
                 }
 
-                var url = 'itemdetails.html?id=' + itemId + '&serverId=' + serverId;
+                var url = 'details?id=' + itemId + '&serverId=' + serverId;
```
Comment (dkanada) [inline src/components/groupedcards.js:25]: Why was this changed?

File: src/scripts/routes.js [hunk 2]
```diff
@@ -234,8 +234,9 @@ define([
         transition: 'fade'
     });
     defineRoute({
-        path: '/itemdetails.html',
-        controller: 'itemDetails',
+        alias: '/details',
+        path: '/controllers/itemDetails/itemDetails.html',
+        controller: 'itemDetails/itemDetails',
```
Comment (dkanada) [inline src/scripts/routes.js:239]: Ah, I see you added that to this pull request. I think the path should assume `controllers` at the beginning since we do the same for the controller. It might also be useful at this point to assume `index.html` and `index.js` and just assume the end of the path is a folder containing both files. This would be relatively standard for pages with Vue.

File: src/scripts/site.js [hunk 3]
```diff
@@ -1129,13 +1129,13 @@ var AppInfo = {};
...
                 if (itemTypes.indexOf(itemType) >= 0) {
-                    return 'itemdetails.html?id=' + id + '&serverId=' + serverId;
+                    return 'details?id=' + id + '&serverId=' + serverId;
                 }
 
                 var contextSuffix = context ? '&context=' + context : '';
 
                 if ('Series' == itemType || 'Season' == itemType || 'Episode' == itemType) {
-                    return 'itemdetails.html?id=' + id + contextSuffix + '&serverId=' + serverId;
+                    return 'details?id=' + id + contextSuffix + '&serverId=' + serverId;
```
Comment (dkanada) [inline src/scripts/site.js:1138]: Rather than use an alias, I would just rename the page `details` since that's accurate enough to make sense.

File: src/controllers/itemDetails/itemDetails.js [hunk 4]
```diff
@@ -409,36 +435,33 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
...
-        var offset = parentNameLast ? '.25em' : '.5em';
 
         if (html && !parentNameLast) {
-            if (!layoutManager.mobile && tvSeasonHtml) {
-                html += '<h3 class="itemName infoText" style="margin: .25em 0 .5em;">' + tvSeasonHtml + ' - ' + name + '</h3>';
+            if (tvSeasonHtml) {
+                html += '<h3 class="itemName infoText subTitle">' + tvSeasonHtml + ' - ' + name + '</h3>';
             } else {
-                html += '<h3 class="itemName infoText" style="margin: .25em 0 .5em;">' + name + '</h3>';
+                html += '<h3 class="itemName infoText subTitle">' + name + '</h3>';
```
Comment (dkanada) [inline src/controllers/itemDetails/itemDetails.js:455]: Unless this is a legacy issue, subtitle is a single word and doesn't need camel casing.

File: src/assets/css/librarybrowser.css [hunk 5]
```diff
@@ -584,6 +653,9 @@
     white-space: nowrap;
     text-overflow: ellipsis;
     text-align: left;
+    min-width: 0;
+    max-width: 100%;
+    overflow: hidden;
```
Comment (dkanada) [inline src/assets/css/librarybrowser.css:658]: I hate using this file as a catch-all for page styles, but we can't really change that yet.

File: src/components/groupedcards.js (hunk 1 above)
Comment (MrTimscampi) [reply src/components/groupedcards.js:25]: The page was moved to the controller, so the URL would be `/controller/itemDetails/itemldetails.html`.

To make it cleaner, I added aliases to the router, so that the routes can be overriden as we cleanup the HTML files in the root folder.

File: src/scripts/site.js (hunk 3 above)
Comment (MrTimscampi) [reply src/scripts/site.js:1138]: The goal is to decouple the path from the name of the endpoint. Currently, the path is used for everything (Path to the HTML and name of the endpoint).

This gives more flexibility, allowing you to separate the two.

We won't have that issue when we move to `vue-router` since at that point it'll be endpoint + component, but in the meantime, I figured this would make for a nice addition.

File: src/scripts/routes.js (hunk 2 above)
Comment (MrTimscampi) [reply src/scripts/routes.js:239]: The issue is that, until we move every HTML page, assuming the beginning of the path isn't going to work.

I'd also argue against assuming things since it makes it slightly harder to understand. Here, you know at a glance the path of the thing.

Getting rid of module aliases while also introducing this kind of thing seems a bit backward :)

File: src/controllers/itemDetails/itemDetails.js [hunk 6]
```diff
@@ -667,18 +644,17 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
     }
 
     function renderLogo(page, item, apiClient) {
+        var detailLogo = page.querySelector('.detailLogo');
+
         var url = logoImageUrl(item, apiClient, {
-            maxWidth: 400
+            maxWidth: detailLogo.clientWidth
```
[the remark this answers is not in the document]
Comment (MrTimscampi) [reply src/controllers/itemDetails/itemDetails.js:653]: I'm thinking about removing the size, since logos can only ever be 800x310 and we crop the white space anyway.

**Comment by MrTimscampi** [comment]
## Updated screenshots

### Before
image
image
image
image
image

### After
image
image
image
image
image

**Comment by Delgan** [comment]
Is there an option to re-enable the labels below the icons? It is difficult to guess the meaning of the icons when you are a new user, I'm afraid it will reduce overall usability. Maybe we could let them enabled by default, and add a css rule to hide them optionally?

**Comment by ferferga** [comment]
@Delgan I think @MrTimscampi is already working in adding tooltips to the icons.

**Comment by MrTimscampi** [comment]
> @Delgan I think @MrTimscampi is already working in adding tooltips to the icons.

The tooltips are in as of b500579 :+1:

**Comment by MrTimscampi** [comment]
> Is there an option to re-enable the labels below the icons? It is difficult to guess the meaning of the icons when you are a new user, I'm afraid it will reduce overall usability. Maybe we could let them enabled by default, and add a css rule to hide them optionally?

All the icons are fairly self-explanatory and, as @ferferga mentioned, we have tooltips on them.

This is very much the same as what Plex is doing, so it should be okay usability-wise.

**Comment by Delgan** [comment]
@ferferga @MrTimscampi Does Jellyfin implement specific behavior to handle `title` attribute on mobile and TV? Like, displaying the tooltip on long-press instead of hover (sorry, I can't test Jellyfin mobile for now)?

I mainly worried about the "Instant Mix" and "Trailer" icons. I wouldn't have known what it meant without the labels. I think they don't negatively affect the design while permitting to be explicit, but it's a matter of taste I guess.

File: src/controllers/itemDetails/index.js [hunk 7]
```diff
@@ -2125,9 +2003,7 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
         view.addEventListener('viewshow', function (e) {
             var page = this;
 
-            if (layoutManager.mobile) {
-                libraryMenu.setTransparentMenu(true);
-            }
+            libraryMenu.setTransparentMenu(true);
```
[the remark this answers is not in the document]
Comment (MrTimscampi) [reply src/controllers/itemDetails/index.js:2006]: It makes the top bar semi-transparent.

File: src/scripts/routes.js [hunk 8]
```diff
@@ -240,8 +240,9 @@ define([
         transition: 'fade'
     });
     defineRoute({
-        path: '/itemdetails.html',
-        controller: 'itemDetails',
+        alias: '/details',
+        path: '/controllers/itemDetails/index.html',
+        controller: 'itemDetails/index',
```
[the remark this answers is not in the document]
Comment (MrTimscampi) [reply src/scripts/routes.js:245]: It still exists for the file yes :) Only the URL is extension-less.

File: src/controllers/itemDetails/index.js [hunk 9]
```diff
@@ -1086,59 +971,62 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
...
             }
         }
 
-        itemMiscInfo = page.querySelectorAll('.itemMiscInfo-secondary');
-        for (i = 0; i < itemMiscInfo.length; i++) {
-            mediaInfo.fillSecondaryMediaInfo(itemMiscInfo[i], item, {
+        const secondaryItemMiscInfo = page.querySelectorAll('.itemMiscInfo-secondary');
+
+        for (const miscInfo of secondaryItemMiscInfo) {
+            mediaInfo.fillSecondaryMediaInfo(miscInfo, item, {
```
[the remark this answers is not in the document]
Comment (MrTimscampi) [reply src/controllers/itemDetails/index.js:994]: It shouldn't. Afaik, the miscInfo variables are contained to the scope of their for loop.

File: src/controllers/itemDetails/index.js [hunk 10]
```diff
@@ -470,43 +497,18 @@ define(['loading', 'appRouter', 'layoutManager', 'connectionManager', 'userSetti
         var imgUrl;
         var hasbackdrop = false;
         var itemBackdropElement = page.querySelector('#itemBackdrop');
-        var usePrimaryImage = item.MediaType === 'Video' && item.Type !== 'Movie' && item.Type !== 'Trailer' ||
-            item.MediaType && item.MediaType !== 'Video' ||
-            item.Type === 'MusicAlbum' ||
-            item.Type === 'Person';
 
-        if (!layoutManager.mobile && !userSettings.detailsBanner()) {
+        if (!layoutManager.mobile && ((!userSettings.enableBackdrops() && !userSettings.detailsBanner()) || (userSettings.enableBackdrops() && !userSettings.detailsBanner()))) {
```
Comment (dmitrylyzo) [inline src/controllers/itemDetails/index.js:501]: Something wrong
`(!X && !Y) || (X && !Y)`
`(!X || X) && !Y`
`!Y`

Comment (MrTimscampi) [reply src/controllers/itemDetails/index.js:501]: Hm, I tested all 4 cases we're going for and it works (Though it's far from pretty)

Comment (dmitrylyzo) [reply src/controllers/itemDetails/index.js:501]: I mean `!userSettings.detailsBanner()` is enough :confused:

**Comment by dkanada** [comment]
Might also be a good idea to test this on a monitor with portrait orientation in that case.

**Comment by ferferga** [comment]
@dkanada Portrait orientation in my desktop looks fine on Desktop layout. Maybe we can narrow the top header, like in mobile. 

**1920x1080**

Sin título

File: src/assets/css/librarybrowser.css [hunk 11]
```diff
@@ -671,6 +671,10 @@
     margin: 1em 0;
 }
 
+.layout-mobile .detailimg-hidemobile {
```
Comment (ferferga) [inline src/assets/css/librarybrowser.css:674]: Any reasoning of this class? Why are we using an specific class just for hiding it in mobile? Can't we use the same class that it's used in other layouts but set it as ``display: none`` when it has layout-mobile as a parent?

Comment (MrTimscampi) [reply src/assets/css/librarybrowser.css]: It was a legacy class. I changed it to `.layout-mobile .detailImageContainer`, which is essentially the same.
