### PR TITLE
Fix baseUrl for web config file

### LINKED ISSUE #1254: Web config is loaded from the wrong URL when the web client is bundled with the server
**Describe the bug**
The web config file and the config template files are loaded from the wrong URL when the web client is being served by the server. For example, `/config.template.json` is used instead of `/web/config.template.json`

**To Reproduce**
1. Follow the instructions to serve the web client from the server: https://github.com/jellyfin/jellyfin#installing-the-web-client
2. Load the web client
3. See that the config file and template are requested from the wrong URL

**Expected behavior**
The config and config template should use the correct URL and load correctly.

**Logs**
From the server logs:
```log
[12:33:12] [ERR] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /config.template
[12:33:12] [ERR] [44] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://localhost:8096/config.template.json   
```
From the web client logs:
```log
cannot get web config: SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" webSettings.js:25:16
```

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Untested due to the server building prrocess being broken.

**Issues**

Fixes #1254

### CODE REVIEW

File: src/scripts/settings/webSettings.js [hunk 1]
```diff
@@ -1,8 +1,12 @@
 let data;
 
+function getBaseUrl() {
+    return location.pathname.substr(0, location.pathname.lastIndexOf('/'));
+}
+
 function getConfig() {
     if (data) return Promise.resolve(data);
-    return fetch('/config.json?nocache=' + new Date().getUTCMilliseconds()).then(response => {
+    return fetch(getBaseUrl() + '/config.json?nocache=' + new Date().getUTCMilliseconds()).then(response => {
```
Comment (dmitrylyzo) [inline src/scripts/settings/webSettings.js:9]: In fact, we can remove leading `/`
```js
fetch('config.json?nocache=' + new Date().getUTCMilliseconds())
```
browser will do the rest.

**Comment by dkanada** [comment]
also fixes #1031
