### PR TITLE
Fix episode overview markdown render

### LINKED ISSUE #5679: Markdown is not displayed correctly on episode's overview preview area.
**Describe The Bug**

Markdown-formatted text works fine in overviews everywhere except for in the overview preview area for episodes. It is not being properly displayed when shown on this display area. If you open the detail view of the episode, the markdown will properly display then.

**Steps To Reproduce**

1. Go to any episode, add in some markdown italics or bold, etc. to the overview in the metadata.
2. Navigate to the episode and see that its preview overview display does not handle markdown correctly as compared to when you open the episode page.

**Expected Behavior**

Markdown should properly display on episode overviews in both views.

**Logs**

N/A

**Screenshots**

[Example of markdown not being displayed correctly](https://i.imgur.com/ZphlWeC.jpeg)
[Same markdown being displayed correctly when the episode detail page is opened](https://i.imgur.com/ixLSGhK.jpeg)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Brave
 - Jellyfin Version: 10.9.6

**Additional Context**

N/A

### PR DESCRIPTION
**Pull request by Chaitanya-Shahare**
**Changes**

- used `markdownIt` to render the markdown in the episode's overview, as expected (and done in detail view of the episode)

**Issues**
Fixes #5679 

**Screenshots**

### Before

image

### After

image

### CODE REVIEW

File: src/components/listview/listview.js [hunk 1]
```diff
@@ -415,8 +416,9 @@ export function getListViewHtml(options) {
         }
 
         if (enableOverview && item.Overview) {
+            const overview = markdownIt().render(item.Overview || '');
```
Comment (dmitrylyzo) [inline src/components/listview/listview.js:419]: To be consistent with the item details, `overview` needs to be sanitized+HTML support as here: https://github.com/jellyfin/jellyfin-web/blob/d04df18ec6f4b6c8ba3d88786e804299fa97dfe9/src/controllers/itemDetails/index.js#L870

This was overlooked.

Comment (Chaitanya-Shahare) [reply src/components/listview/listview.js:419]: I'll make this change.

**Comment by Shadowghost** [comment]
Should this be PRed agains 10.9 since it's technically a bugfix?

**Comment by Chaitanya-Shahare** [comment]
> Should this be PRed agains 10.9 since it's technically a bugfix?



I'm new to this repository, so please excuse me if this is obvious.

Do I have to make any changes to this PR?

**Comment by dmitrylyzo** [comment]
> Do I have to make any changes to this PR?

Personally, I consider this PR as a bugfix because we use Markdown+HTML in the item details (#4393) but forgot to do the same in the episode list (_this PR_).
This PR also fixes possible XSS vulnerability (by sanitizing `Overview`).
Thus, it should target the release branch.

1. Rebase your branch in the interactive mode on `release-10.9.z` branch, leaving only related commits.
2. Verify that everything is correct (_Currently there should be your 3 commits over the release branch. Actually, I would squash them in one commit_). Force push your rebased branch to your repo. This PR will conflict, but don't worry.
3. Change the target branch from `master` to `release-10.9.z` using the `Edit` button next to the title of PR.

**Comment by Chaitanya-Shahare** [comment]
> > Do I have to make any changes to this PR?
> 
> Personally, I consider this PR as a bugfix because we use Markdown+HTML in the item details (#4393) but forgot to do the same in the episode list (_this PR_). This PR also fixes possible XSS vulnerability (by sanitizing `Overview`). Thus, it should target the release branch.
> 
> 1. Rebase your branch in the interactive mode on `release-10.9.z` branch, leaving only related commits.
> 2. Verify that everything is correct (_Currently there should be your 3 commits over the release branch. Actually, I would squash them in one commit_). Force push your rebased branch to your repo. This PR will conflict, but don't worry.
> 3. Change the target branch from `master` to `release-10.9.z` using the `Edit` button next to the title of PR.

Thank you for the instructions, I'll do this.

**Review by thornbill — APPROVED** [review]
