### PR TITLE
Ensure that fillHeight gets set on image requests

### LINKED ISSUE #2191: 10.7.2 uses a very low resolution for images in "next up" home section.
**Describe The Bug**
image
Crispy high resolution image. All other sections work fine.

The HTTP request to the image uses this url:
`https://jellyfin/Items/895ed51c4c595d404855abcc06d81d11/Images/Backdrop?maxWidth=355&tag=61a4233cbf0e9cde73d1b8933c4fcb19&quality=80`

The returned image is 355x75. Which is totally wrong.
image

### LINKED ISSUE #2587: [10.7.2] No poster images / Low quality card images on high DPI displays
**Describe The Bug**
Since the last 10.7.2 update I'm seeing low quality images being used for the cards (posters, thumbs and library images). This is a Jellyfin Web issue as I can see them in high quality using Jellyfin Vue.

**Steps To Reproduce**
1. Update to 10.7.2
2. Go to the main page and look at the card images

**Expected Behavior**
Clear and high quality images being used for the cards.

**Screenshots**
Jellyfin Web:
image
image
image

Jellyfin Vue:
image
image
image

**System (please complete the following information):**
 - Platform: Docker 20.10.5 on Ubuntu Server 20.04.2 LTS
 - Browser: Edge Chromium 91.0.845.2 (Dev)
 - Jellyfin Version: 10.7.2 (Hotio Docker image)

### PR DESCRIPTION
**Pull request by oddstr13**
**Changes**

- Ensure that fillHeight gets set in the image request
- Request quality of 96, for up to 16 less jpeg
- Bump apiclient to 1.7.0

**Issues**

- Fixes #2191 
- Fixes #2587 

**Notes**

The backport requires the yarn lockfile (`yarn.lock`) updated rather than the npm one (`package-lock.json`).
Discard the changes to `package-lock.json`, and generate the update to `yarn.lock` from `package.json` using the following command;
`docker run -it -v "$(pwd):/mnt" --rm node:lts bash -c 'cd /mnt; yarn install'` (takes a long time, downloads all deps too)

The result of this can be seen at this branch targeting the release branch: https://github.com/jellyfin/jellyfin-web/compare/v10.7.2...oddstr13:pr-imagefix

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]
Can confirm fixed 👍

File: src/components/cardbuilder/cardBuilder.js [hunk 1]
```diff
@@ -498,7 +498,7 @@ import ServerConnections from '../ServerConnections';
             let imgUrl = null;
             let imgTag = null;
             let coverImage = false;
-            let uiAspect = null;
+            let uiAspect = getDesiredAspect(shape);
```
Comment (oddstr13) [inline src/components/cardbuilder/cardBuilder.js:501]:
```suggestion
            const uiAspect = getDesiredAspect(shape);
```
