### PR TITLE
Fix dialog closing flow

### LINKED ISSUE #3978: Unable to change screen ratio
Hi,
When viewing live stream, click on the right settings wheel, the mini setting screens pop up,
When I'm trying to click on the aspect ratio, it just close the mini setting and go back to the video.

Please advise,
Thanks

### PR DESCRIPTION
**Pull request by dmitrylyzo**
**Changes**
When closing the dialog, wait for the browser history to finish updating the state.

**Issues**
Fixes #3978

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]

File: src/components/dialogHelper/dialogHelper.js [hunk 1]
```diff
@@ -92,9 +110,13 @@ import '../../assets/css/scrollstyles.scss';
                 const state = history.location.state || {};
                 if (state.dialogs?.length > 0) {
                     if (state.dialogs[state.dialogs.length - 1] === hash) {
+                        unlisten = history.listen(finishClose);
                         history.back();
                     } else if (state.dialogs.includes(hash)) {
                         console.warn('[dialogHelper] dialog "%s" was closed, but is not the last dialog opened', hash);
+
+                        unlisten = history.listen(finishClose);
```
Comment (dmitrylyzo) [inline src/components/dialogHelper/dialogHelper.js:118]: probably wrong - `replaceState` doesn't emit `popstate`

Comment (dmitrylyzo) [reply src/components/dialogHelper/dialogHelper.js:118]: It's fine - `history` calls the callback itself.

**Review by thornbill — APPROVED** [review]
