### PR TITLE
Details page artwork ribbon revamp

### LINKED ISSUE #820: Header art is too big on movie details page
**Describe the bug**
The header art is too big on the movie details page. It obscures the poster and other details (cast and similar movies)

**Expected behavior**
Solution is not clear. In my opinion, it should be removed and displayed only as a backdrop.

**Screenshots**
out

**System (please complete the following information):**
 - Browser: Firefox 73
 - Jellyfin Version: 20200216 nightly

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Rework of the artwork on the details page.

ded19b1 - Hides the artwork ribbon (backdrop and logo) if the user has disabled the backdrops. Adjusts the position of the details and the poster to compensate for the backdrop ribbon not being shown.

e0dc32c  - Moves the poster and sticky bar, removes the stickyness.

Further commits fix up the layout when no backdrop is there.

image

image

**Issues**

Fixes #820

### CODE REVIEW

File: src/controllers/itemdetailpage.js [hunk 1]
```diff
@@ -457,20 +457,25 @@ define(["loading", "appRouter", "layoutManager", "connectionManager", "cardBuild
         var imgUrl;
         var screenWidth = screen.availWidth;
         var hasbackdrop = false;
+        console.debug(page);
```
Comment (dkanada) [inline src/controllers/itemdetailpage.js]: maybe remove this

File: src/controllers/itemdetailpage.js [hunk 2]
```diff
@@ -1047,6 +1055,8 @@ define(["loading", "appRouter", "layoutManager", "connectionManager", "cardBuild
     }
 
     function renderDetails(page, item, apiClient, context, isStatic) {
+        var taglineElement = page.querySelector(".detailPageContent");
```
Comment (dkanada) [inline src/controllers/itemdetailpage.js]: Is this used somewhere below?

**Comment by MrTimscampi** [comment]
> It might be better to keep the same detail sticky placement without a backdrop and simply remove the background color change.

The issue is that then, we're losing a ton of space to what is essentially blank space. For example, it doesn't make sense for actors or media types where there will pretty much never be a backdrop, then it's simply wasted space.

As an aside, I removed all the dead code pointed out by ESLint in itemdetailspage.js. It was doing API calls to get user details that were never used afterwards, as well as passing completely useless parameters to some of the methods.

File: src/assets/css/librarybrowser.css [hunk 3]
```diff
@@ -439,10 +439,43 @@
...
     position: relative;
 }
 
+.layout-desktop .itemBackdrop::after,
+.layout-tv .itemBackdrop::after {
+    content: "";
+    width: 100%;
+    height: 100%;
+    background: #000000ad;
+    background: rgba(0, 0, 0, 0.65);
```
Comment (JustAMan) [inline src/assets/css/librarybrowser.css]: uh?

File: src/controllers/itemdetailpage.js [hunk 4]
```diff
@@ -464,13 +462,17 @@ define(["loading", "appRouter", "layoutManager", "connectionManager", "cardBuild
             item.Type === "MusicArtist" ||
             item.Type === "Person";
 
+        if (!layoutManager.mobile && !userSettings.enableBackdrops()) {
+            return hasbackdrop;
```
Comment (JustAMan) [inline src/controllers/itemdetailpage.js]:
```suggestion
            return false;
```
for clarity?

File: src/controllers/itemdetailpage.js [hunk 5]
```diff
@@ -506,15 +508,15 @@ define(["loading", "appRouter", "layoutManager", "connectionManager", "cardBuild
                 index: 0,
                 tag: item.ImageTags.Thumb
             });
-            itemBackdropElement.classList.remove("noBackdrop");
+            page.classList.remove("noBackdrop");
             imageLoader.lazyImage(itemBackdropElement, imgUrl, false);
             hasbackdrop = true;
         } else {
-            itemBackdropElement.classList.add("noBackdrop");
```
Comment (JustAMan) [inline src/controllers/itemdetailpage.js]: why?

File: src/controllers/itemdetailpage.js [hunk 6]
```diff
@@ -506,15 +508,15 @@ define(["loading", "appRouter", "layoutManager", "connectionManager", "cardBuild
...
             itemBackdropElement.style.backgroundImage = "";
         }
 
         if ("Person" === item.Type) {
+            page.classList.add('noBackdrop');
```
Comment (JustAMan) [inline src/controllers/itemdetailpage.js]: why?

File: src/assets/css/librarybrowser.css (hunk 3 above)
Comment (MrTimscampi) [reply src/assets/css/librarybrowser.css]: It's from aivit's code for this.

Not really needed nowadays to have the hex fallback, but it doesn't hurt (I can remove it tonight if needed).

File: src/controllers/itemdetailpage.js (hunk 5 above)
Comment (MrTimscampi) [reply src/controllers/itemdetailpage.js]: The noBackdrop class is now at the very top of the page, so everything below it has access to it. No need to add it elsewhere.

File: src/controllers/itemdetailpage.js (hunk 6 above)
Comment (MrTimscampi) [reply src/controllers/itemdetailpage.js]: Person's seldom have a backdrop. There's likely a better way to handle this case, though.

Comment (JustAMan) [reply src/controllers/itemdetailpage.js]: add a `//FIXME` comment explaining this case then, please
