### PR TITLE
Fix playback interceptor rejecting

### LINKED ISSUE #5568: Disabling media playback doesn't work as intended
**Describe The Bug**
Disabling media playback for any user doesn't seem to work as intended. Initially it does show the prompt saying "Playback of this content is currently restricted.Please contact your server administrator for more information." But as soon as user clicks on the button saying "Got It" the video actually starts playing

**Steps To Reproduce**

1. Go to Dashboard
2. Click on Users
3. Scroll down to Media Playback
4. Untick "Allow media playback"

**Expected Behavior**
Video should be not played after that prompt. It should simply exit

**Logs**
```
[2024-05-20 21:38:39.691 +05:30] [INF] [181] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2024-05-20 21:38:39.822 +05:30] [INF] [185] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "2b78ec39f1f7c76c61651d1c3a074430bc3cb2e2562a5be8-61651d1c3a074430bc3cb2e2562a5be8-a90354da96fdd08a51c91dfe37d0c412"
[2024-05-20 21:38:47.905 +05:30] [INF] [190] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Android" "2.6.1" playing "6 Underground". Stopped at "5580" ms
[2024-05-20 21:38:47.910 +05:30] [INF] [185] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "2b78ec39f1f7c76c61651d1c3a074430bc3cb2e2562a5be8-61651d1c3a074430bc3cb2e2562a5be8-a90354da96fdd08a51c91dfe37d0c412"
[2024-05-20 21:38:47.910 +05:30] [INF] [185] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 05/20/2024 21:38:47
[2024-05-20 21:38:47.910 +05:30] [INF] [185] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[2024-05-20 21:38:49.838 +05:30] [INF] [178] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "110.226.178.205" closed
[2024-05-20 21:38:49.841 +05:30] [INF] [185] Emby.Server.Implementations.Session.SessionManager: Logging out access token "1bc9ec9e311a4f3887420a4ccaf5c9ce"
[2024-05-20 21:38:52.128 +05:30] [INF] [178] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
[2024-05-20 21:38:53.141 +05:30] [INF] [178] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.
```

**Screenshots**
IMG_20240520_213110_194

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Brave
 - Jellyfin Version: v10.9.2

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
* Fixes a regression from #5402 where access checks fall through to getting the saved bitrate when rejecting allowing users to play media they don't have access to after closing the dialog

The code is pretty gross, but I don't want to touch this too much in a backport PR

**Issues**
Fixes #5568

### CODE REVIEW

File: src/components/playback/playbackmanager.js [hunk 1]
```diff
@@ -2502,6 +2492,33 @@ class PlaybackManager {
             }
         }
 
+        function detectBitrate(apiClient, item, mediaType, playOptions) {
+            // FIXME: This is gnarly, but don't want to change too much here in a bugfix
+            return Promise.resolve()
+                .then(() => {
+                    if (playOptions.fullscreen) {
+                        loading.show();
+                    }
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:2501]: Can we move this to `then` in between:
https://github.com/jellyfin/jellyfin-web/blob/70b9aa46114b3d60435499e33a85b93c162ecaa9/src/components/playback/playbackmanager.js#L2287-L2288
so that `loading.show/hide` are not split over the code?

File: src/components/playback/playbackmanager.js [hunk 2]
```diff
@@ -2343,7 +2333,7 @@ class PlaybackManager {
 
             showPlaybackInfoErrorMessage(self, displayErrorCode);
 
-            return Promise.reject();
+            return Promise.resolve();
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:2336]: Doesn't this mean that `play` will be resolved rather than rejected?

File: src/components/playback/playbackmanager.js [hunk 3]
```diff
@@ -2267,7 +2267,7 @@ class PlaybackManager {
             if (item.IsPlaceHolder) {
                 loading.hide();
                 showPlaybackInfoErrorMessage(self, 'PlaybackErrorPlaceHolder');
-                return Promise.reject();
+                return Promise.resolve();
```
Comment (dmitrylyzo) [inline src/components/playback/playbackmanager.js:2270]: Rejected `play`?

Comment (thornbill) [reply src/components/playback/playbackmanager.js:2270]: It doesn't seem like we handle rejections from this function... the normal branch never rejects due to the `finally`. This fixes an unhandled promise rejection error.

File: src/components/playback/playbackmanager.js (hunk 2 above)
Comment (thornbill) [reply src/components/playback/playbackmanager.js:2336]: Yes but the `catch` does nothing and the `finally` means the function always resolves overall.

Comment (dmitrylyzo) [reply src/components/playback/playbackmanager.js:2336]: I thought that `finally` returns a promise with the same state of error. The original code (before #5402) returned a rejected promise, so it is better to keep this.

Comment (thornbill) [reply src/components/playback/playbackmanager.js:2336]: Yeah you are right about `finally`. I don't know why I can never keep that straight. :sweat_smile:

File: src/components/playback/playbackmanager.js (hunk 3 above)
Comment (thornbill) [reply src/components/playback/playbackmanager.js:2270]: :thinking: ok so not a single place this is called handles promise rejections... I guess that is fine since it's the current state of things?

**Review by nielsvanvelzen — APPROVED** [review]

**Review by dmitrylyzo — APPROVED** [review]
