### PR TITLE
Use TV layout by default on PS4

### LINKED ISSUE #1054: Playstation 4 is not recogniced as TV
**Describe the bug**
The web browser of the PS4 is not recognized as a TV, therefore the desktop layout is used instead of the TV layout.
After switching to the TV layout, the focus is working fine, but the select does not work correct, it selects where the cursor is and not the current focused item.

Also in the OSD the AirPlay icon is visible which should not be the case

**To Reproduce**
Open JF with the PS4 web browser

**Expected behavior**
The layout should be the TV layout and the focused item should be selected and not the item behind the hidden cursor.

**System (please complete the following information):**
 - OS: Windows (Server)
 - Browser: PS4 Browser
 - Jellyfin Version: 10.5.2

### PR DESCRIPTION
**Pull request by MrTimscampi**
**Changes**

Sets the TV layout as the default layout or PS4.

**Issues**

Fixes #1054

### CODE REVIEW

File: src/components/apphost.js [hunk 1]
```diff
@@ -237,10 +237,6 @@ define(["appSettings", "browser", "events", "htmlMediaHelper", "webSettings"], f
             features.push("voiceinput");
         }
 
-        if (!browser.tv && !browser.xboxOne) {
-            browser.ps4;
-        }
```
Comment (dkanada) [inline src/components/apphost.js:242]: What was this even doing?

Comment (MrTimscampi) [reply src/components/apphost.js:242]: ¯\\\_(ツ)\_/¯
